// Code generated by bitproto-go native renderer (experimental). DO NOT EDIT.
#ifndef __BITPROTO__DRONE_H__
#define __BITPROTO__DRONE_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

typedef int64_t Timestamp;
typedef int32_t TernaryInt32[3];

typedef uint8_t DroneStatus;
#define DRONE_STATUS_UNKNOWN 0
#define DRONE_STATUS_STANDBY 1
#define DRONE_STATUS_RISING 2
#define DRONE_STATUS_LANDING 3
#define DRONE_STATUS_FLYING 4

typedef uint8_t PropellerStatus;
#define PROPELLER_STATUS_UNKNOWN 0
#define PROPELLER_STATUS_IDLE 1
#define PROPELLER_STATUS_ROTATING 2

typedef uint8_t RotatingDirection;
#define ROTATING_DIRECTION_UNKNOWN 0
#define ROTATING_DIRECTION_CLOCK_WISE 1
#define ROTATING_DIRECTION_ANTI_CLOCK_WISE 2

typedef uint8_t PowerStatus;
#define POWER_STATUS_UNKNOWN 0
#define POWER_STATUS_OFF 1
#define POWER_STATUS_ON 2

typedef uint8_t LandingGearStatus;
#define LANDING_GEAR_STATUS_UNKNOWN 0
#define LANDING_GEAR_STATUS_UNFOLDED 1
#define LANDING_GEAR_STATUS_FOLDED 2

struct Propeller {
    uint8_t id;
    PropellerStatus status;
    RotatingDirection direction;
};

struct Power {
    uint8_t battery;
    PowerStatus status;
    bool is_charging;
};

struct Network {
    uint8_t signal;
    Timestamp heartbeat_at;
};

struct LandingGear {
    LandingGearStatus status;
};

struct Position {
    int32_t latitude;
    int32_t longitude;
    int32_t altitude;
};

struct Pose {
    int32_t yaw;
    int32_t pitch;
    int32_t roll;
};

struct Flight {
    struct Pose pose;
    TernaryInt32 velocity;
    TernaryInt32 acceleration;
};

struct Drone {
    DroneStatus status;
    struct Position position;
    struct Flight flight;
    struct Propeller propellers[4];
    struct Power power;
    struct Network network;
    struct LandingGear landing_gear;
};

#define BYTES_LENGTH_PROPELLER 2
#define BYTES_LENGTH_POWER 2
#define BYTES_LENGTH_NETWORK 9
#define BYTES_LENGTH_LANDINGGEAR 1
#define BYTES_LENGTH_POSITION 12
#define BYTES_LENGTH_POSE 12
#define BYTES_LENGTH_FLIGHT 36
#define BYTES_LENGTH_DRONE 65

size_t EncodePropeller(struct Propeller *m, unsigned char *s);
size_t DecodePropeller(struct Propeller *m, unsigned char *s);
int JsonPropeller(struct Propeller *m, char *s);
size_t EncodePower(struct Power *m, unsigned char *s);
size_t DecodePower(struct Power *m, unsigned char *s);
int JsonPower(struct Power *m, char *s);
size_t EncodeNetwork(struct Network *m, unsigned char *s);
size_t DecodeNetwork(struct Network *m, unsigned char *s);
int JsonNetwork(struct Network *m, char *s);
size_t EncodeLandingGear(struct LandingGear *m, unsigned char *s);
size_t DecodeLandingGear(struct LandingGear *m, unsigned char *s);
int JsonLandingGear(struct LandingGear *m, char *s);
size_t EncodePosition(struct Position *m, unsigned char *s);
size_t DecodePosition(struct Position *m, unsigned char *s);
int JsonPosition(struct Position *m, char *s);
size_t EncodePose(struct Pose *m, unsigned char *s);
size_t DecodePose(struct Pose *m, unsigned char *s);
int JsonPose(struct Pose *m, char *s);
size_t EncodeFlight(struct Flight *m, unsigned char *s);
size_t DecodeFlight(struct Flight *m, unsigned char *s);
int JsonFlight(struct Flight *m, char *s);
size_t EncodeDrone(struct Drone *m, unsigned char *s);
size_t DecodeDrone(struct Drone *m, unsigned char *s);
int JsonDrone(struct Drone *m, char *s);

static inline void SetPositionLatitudeFloat(struct Position *m, double v) { m->latitude = BpFloatToInt32(v); }
static inline double GetPositionLatitudeFloat(const struct Position *m) { return BpInt32ToFloat(m->latitude); }
static inline void SetPositionLongitudeFloat(struct Position *m, double v) { m->longitude = BpFloatToInt32(v); }
static inline double GetPositionLongitudeFloat(const struct Position *m) { return BpInt32ToFloat(m->longitude); }
static inline void SetPositionAltitudeFloat(struct Position *m, double v) { m->altitude = BpFloatToInt32(v); }
static inline double GetPositionAltitudeFloat(const struct Position *m) { return BpInt32ToFloat(m->altitude); }

#if defined(__cplusplus)
}
#endif

#endif
