// Code generated by bitproto. DO NOT EDIT.

#include "drone_bp.h"
#if !defined(BP_BIG_ENDIAN) && (\
    (defined(__BYTE_ORDER__) && (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)) || \
    defined(__ARM_BIG_ENDIAN) || \
    defined(__big_endian__) || \
    defined(__BIG_ENDIAN__) || \
    (defined(__LITTLE_ENDIAN__) && (__LITTLE_ENDIAN__ == 0)))
#define BP_BIG_ENDIAN 1
#endif
#ifdef BP_BIG_ENDIAN
#include <string.h>
#endif

size_t EncodePropeller(struct Propeller *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    s[0] = (((unsigned char *)&((*m).id))[0] ) & 255;
    s[1] = (((unsigned char *)&((*m).status))[0] ) & 3;
    s[1] |= (((unsigned char *)&((*m).direction))[0] << 2) & 12;
#else
    s[0] = ((uint8_t)((*m).id)) & 255;
    s[1] = ((uint8_t)((*m).status)) & 3;
    s[1] |= ((uint8_t)((*m).direction)<< 2) & 12;
#endif
    return BYTES_LENGTH_PROPELLER;
}

size_t DecodePropeller(struct Propeller *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    ((unsigned char *)&((*m).id))[0] = (s[0] ) & 255;
    ((unsigned char *)&((*m).status))[0] = (s[1] ) & 3;
    ((unsigned char *)&((*m).direction))[0] = (s[1] >> 2) & 3;
#else
    memset(m, 0, sizeof(*m));
    (*m).id |= (uint8_t)(((unsigned)(s[0])) & 255);
    (*m).status |= (PropellerStatus)(((unsigned)(s[1])) & 3);
    (*m).direction |= (RotatingDirection)(((unsigned)(s[1])>> 2) & 3);
#endif
    return BYTES_LENGTH_PROPELLER;
}

size_t EncodePower(struct Power *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    s[0] = (((unsigned char *)&((*m).battery))[0] ) & 255;
    s[1] = (((unsigned char *)&((*m).status))[0] ) & 3;
    s[1] |= (((unsigned char *)&((*m).is_charging))[0] << 2) & 4;
#else
    s[0] = ((uint8_t)((*m).battery)) & 255;
    s[1] = ((uint8_t)((*m).status)) & 3;
    s[1] |= ((uint8_t)((*m).is_charging)<< 2) & 4;
#endif
    return BYTES_LENGTH_POWER;
}

size_t DecodePower(struct Power *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    ((unsigned char *)&((*m).battery))[0] = (s[0] ) & 255;
    ((unsigned char *)&((*m).status))[0] = (s[1] ) & 3;
    ((unsigned char *)&((*m).is_charging))[0] = (s[1] >> 2) & 1;
#else
    memset(m, 0, sizeof(*m));
    (*m).battery |= (uint8_t)(((unsigned)(s[0])) & 255);
    (*m).status |= (PowerStatus)(((unsigned)(s[1])) & 3);
    (*m).is_charging |= (bool)(((unsigned)(s[1])>> 2) & 1);
#endif
    return BYTES_LENGTH_POWER;
}

size_t EncodeNetwork(struct Network *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    s[0] = (((unsigned char *)&((*m).signal))[0] ) & 15;
    s[0] |= (((unsigned char *)&((*m).heartbeat_at))[0] << 4) & 240;
    s[1] = (((unsigned char *)&((*m).heartbeat_at))[0] >> 4) & 15;
    s[1] |= (((unsigned char *)&((*m).heartbeat_at))[1] << 4) & 240;
    s[2] = (((unsigned char *)&((*m).heartbeat_at))[1] >> 4) & 15;
    s[2] |= (((unsigned char *)&((*m).heartbeat_at))[2] << 4) & 240;
    s[3] = (((unsigned char *)&((*m).heartbeat_at))[2] >> 4) & 15;
    s[3] |= (((unsigned char *)&((*m).heartbeat_at))[3] << 4) & 240;
    s[4] = (((unsigned char *)&((*m).heartbeat_at))[3] >> 4) & 15;
    s[4] |= (((unsigned char *)&((*m).heartbeat_at))[4] << 4) & 240;
    s[5] = (((unsigned char *)&((*m).heartbeat_at))[4] >> 4) & 15;
    s[5] |= (((unsigned char *)&((*m).heartbeat_at))[5] << 4) & 240;
    s[6] = (((unsigned char *)&((*m).heartbeat_at))[5] >> 4) & 15;
    s[6] |= (((unsigned char *)&((*m).heartbeat_at))[6] << 4) & 240;
    s[7] = (((unsigned char *)&((*m).heartbeat_at))[6] >> 4) & 15;
    s[7] |= (((unsigned char *)&((*m).heartbeat_at))[7] << 4) & 240;
    s[8] = (((unsigned char *)&((*m).heartbeat_at))[7] >> 4) & 15;
#else
    s[0] = ((uint8_t)((*m).signal)) & 15;
    s[0] |= ((uint64_t)((*m).heartbeat_at)<< 4) & 240;
    s[1] = ((uint64_t)((*m).heartbeat_at)>> 4) & 15;
    s[1] |= ((uint64_t)((*m).heartbeat_at)>> 4) & 240;
    s[2] = ((uint64_t)((*m).heartbeat_at)>> 12) & 15;
    s[2] |= ((uint64_t)((*m).heartbeat_at)>> 12) & 240;
    s[3] = ((uint64_t)((*m).heartbeat_at)>> 20) & 15;
    s[3] |= ((uint64_t)((*m).heartbeat_at)>> 20) & 240;
    s[4] = ((uint64_t)((*m).heartbeat_at)>> 28) & 15;
    s[4] |= ((uint64_t)((*m).heartbeat_at)>> 28) & 240;
    s[5] = ((uint64_t)((*m).heartbeat_at)>> 36) & 15;
    s[5] |= ((uint64_t)((*m).heartbeat_at)>> 36) & 240;
    s[6] = ((uint64_t)((*m).heartbeat_at)>> 44) & 15;
    s[6] |= ((uint64_t)((*m).heartbeat_at)>> 44) & 240;
    s[7] = ((uint64_t)((*m).heartbeat_at)>> 52) & 15;
    s[7] |= ((uint64_t)((*m).heartbeat_at)>> 52) & 240;
    s[8] = ((uint64_t)((*m).heartbeat_at)>> 60) & 15;
#endif
    return BYTES_LENGTH_NETWORK;
}

size_t DecodeNetwork(struct Network *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    ((unsigned char *)&((*m).signal))[0] = (s[0] ) & 15;
    ((unsigned char *)&((*m).heartbeat_at))[0] = (s[0] >> 4) & 15;
    ((unsigned char *)&((*m).heartbeat_at))[0] |= (s[1] << 4) & 240;
    ((unsigned char *)&((*m).heartbeat_at))[1] = (s[1] >> 4) & 15;
    ((unsigned char *)&((*m).heartbeat_at))[1] |= (s[2] << 4) & 240;
    ((unsigned char *)&((*m).heartbeat_at))[2] = (s[2] >> 4) & 15;
    ((unsigned char *)&((*m).heartbeat_at))[2] |= (s[3] << 4) & 240;
    ((unsigned char *)&((*m).heartbeat_at))[3] = (s[3] >> 4) & 15;
    ((unsigned char *)&((*m).heartbeat_at))[3] |= (s[4] << 4) & 240;
    ((unsigned char *)&((*m).heartbeat_at))[4] = (s[4] >> 4) & 15;
    ((unsigned char *)&((*m).heartbeat_at))[4] |= (s[5] << 4) & 240;
    ((unsigned char *)&((*m).heartbeat_at))[5] = (s[5] >> 4) & 15;
    ((unsigned char *)&((*m).heartbeat_at))[5] |= (s[6] << 4) & 240;
    ((unsigned char *)&((*m).heartbeat_at))[6] = (s[6] >> 4) & 15;
    ((unsigned char *)&((*m).heartbeat_at))[6] |= (s[7] << 4) & 240;
    ((unsigned char *)&((*m).heartbeat_at))[7] = (s[7] >> 4) & 15;
    ((unsigned char *)&((*m).heartbeat_at))[7] |= (s[8] << 4) & 240;
#else
    memset(m, 0, sizeof(*m));
    (*m).signal |= (uint8_t)(((unsigned)(s[0])) & 15);
    (*m).heartbeat_at |= (Timestamp)(((unsigned)(s[0])>> 4) & 15);
    (*m).heartbeat_at |= (Timestamp)(((unsigned)(s[1])<< 4) & 240);
    (*m).heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[1])>> 4) & 15) << 8);
    (*m).heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[2])<< 4) & 240) << 8);
    (*m).heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[2])>> 4) & 15) << 16);
    (*m).heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[3])<< 4) & 240) << 16);
    (*m).heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[3])>> 4) & 15) << 24);
    (*m).heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[4])<< 4) & 240) << 24);
    (*m).heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[4])>> 4) & 15) << 32);
    (*m).heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[5])<< 4) & 240) << 32);
    (*m).heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[5])>> 4) & 15) << 40);
    (*m).heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[6])<< 4) & 240) << 40);
    (*m).heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[6])>> 4) & 15) << 48);
    (*m).heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[7])<< 4) & 240) << 48);
    (*m).heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[7])>> 4) & 15) << 56);
    (*m).heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[8])<< 4) & 240) << 56);
#endif
    return BYTES_LENGTH_NETWORK;
}

size_t EncodeLandingGear(struct LandingGear *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    s[0] = (((unsigned char *)&((*m).status))[0] ) & 3;
#else
    s[0] = ((uint8_t)((*m).status)) & 3;
#endif
    return BYTES_LENGTH_LANDING_GEAR;
}

size_t DecodeLandingGear(struct LandingGear *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    ((unsigned char *)&((*m).status))[0] = (s[0] ) & 3;
#else
    memset(m, 0, sizeof(*m));
    (*m).status |= (LandingGearStatus)(((unsigned)(s[0])) & 3);
#endif
    return BYTES_LENGTH_LANDING_GEAR;
}

size_t EncodePosition(struct Position *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    s[0] = (((unsigned char *)&((*m).latitude))[0] ) & 255;
    s[1] = (((unsigned char *)&((*m).latitude))[1] ) & 255;
    s[2] = (((unsigned char *)&((*m).latitude))[2] ) & 255;
    s[3] = (((unsigned char *)&((*m).latitude))[3] ) & 255;
    s[4] = (((unsigned char *)&((*m).longitude))[0] ) & 255;
    s[5] = (((unsigned char *)&((*m).longitude))[1] ) & 255;
    s[6] = (((unsigned char *)&((*m).longitude))[2] ) & 255;
    s[7] = (((unsigned char *)&((*m).longitude))[3] ) & 255;
    s[8] = (((unsigned char *)&((*m).altitude))[0] ) & 255;
    s[9] = (((unsigned char *)&((*m).altitude))[1] ) & 255;
    s[10] = (((unsigned char *)&((*m).altitude))[2] ) & 255;
    s[11] = (((unsigned char *)&((*m).altitude))[3] ) & 255;
#else
    s[0] = ((uint32_t)((*m).latitude)) & 255;
    s[1] = ((uint32_t)((*m).latitude)>> 8) & 255;
    s[2] = ((uint32_t)((*m).latitude)>> 16) & 255;
    s[3] = ((uint32_t)((*m).latitude)>> 24) & 255;
    s[4] = ((uint32_t)((*m).longitude)) & 255;
    s[5] = ((uint32_t)((*m).longitude)>> 8) & 255;
    s[6] = ((uint32_t)((*m).longitude)>> 16) & 255;
    s[7] = ((uint32_t)((*m).longitude)>> 24) & 255;
    s[8] = ((uint32_t)((*m).altitude)) & 255;
    s[9] = ((uint32_t)((*m).altitude)>> 8) & 255;
    s[10] = ((uint32_t)((*m).altitude)>> 16) & 255;
    s[11] = ((uint32_t)((*m).altitude)>> 24) & 255;
#endif
    return BYTES_LENGTH_POSITION;
}

size_t DecodePosition(struct Position *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    ((unsigned char *)&((*m).latitude))[0] = (s[0] ) & 255;
    ((unsigned char *)&((*m).latitude))[1] = (s[1] ) & 255;
    ((unsigned char *)&((*m).latitude))[2] = (s[2] ) & 255;
    ((unsigned char *)&((*m).latitude))[3] = (s[3] ) & 255;
    ((unsigned char *)&((*m).longitude))[0] = (s[4] ) & 255;
    ((unsigned char *)&((*m).longitude))[1] = (s[5] ) & 255;
    ((unsigned char *)&((*m).longitude))[2] = (s[6] ) & 255;
    ((unsigned char *)&((*m).longitude))[3] = (s[7] ) & 255;
    ((unsigned char *)&((*m).altitude))[0] = (s[8] ) & 255;
    ((unsigned char *)&((*m).altitude))[1] = (s[9] ) & 255;
    ((unsigned char *)&((*m).altitude))[2] = (s[10] ) & 255;
    ((unsigned char *)&((*m).altitude))[3] = (s[11] ) & 255;
#else
    memset(m, 0, sizeof(*m));
    (*m).latitude |= (uint32_t)(((unsigned)(s[0])) & 255);
    (*m).latitude |= (uint32_t)((uint32_t)(((unsigned)(s[1])) & 255) << 8);
    (*m).latitude |= (uint32_t)((uint32_t)(((unsigned)(s[2])) & 255) << 16);
    (*m).latitude |= (uint32_t)((uint32_t)(((unsigned)(s[3])) & 255) << 24);
    (*m).longitude |= (uint32_t)(((unsigned)(s[4])) & 255);
    (*m).longitude |= (uint32_t)((uint32_t)(((unsigned)(s[5])) & 255) << 8);
    (*m).longitude |= (uint32_t)((uint32_t)(((unsigned)(s[6])) & 255) << 16);
    (*m).longitude |= (uint32_t)((uint32_t)(((unsigned)(s[7])) & 255) << 24);
    (*m).altitude |= (uint32_t)(((unsigned)(s[8])) & 255);
    (*m).altitude |= (uint32_t)((uint32_t)(((unsigned)(s[9])) & 255) << 8);
    (*m).altitude |= (uint32_t)((uint32_t)(((unsigned)(s[10])) & 255) << 16);
    (*m).altitude |= (uint32_t)((uint32_t)(((unsigned)(s[11])) & 255) << 24);
#endif
    return BYTES_LENGTH_POSITION;
}

size_t EncodePose(struct Pose *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    s[0] = (((unsigned char *)&((*m).yaw))[0] ) & 255;
    s[1] = (((unsigned char *)&((*m).yaw))[1] ) & 255;
    s[2] = (((unsigned char *)&((*m).yaw))[2] ) & 255;
    s[3] = (((unsigned char *)&((*m).yaw))[3] ) & 255;
    s[4] = (((unsigned char *)&((*m).pitch))[0] ) & 255;
    s[5] = (((unsigned char *)&((*m).pitch))[1] ) & 255;
    s[6] = (((unsigned char *)&((*m).pitch))[2] ) & 255;
    s[7] = (((unsigned char *)&((*m).pitch))[3] ) & 255;
    s[8] = (((unsigned char *)&((*m).roll))[0] ) & 255;
    s[9] = (((unsigned char *)&((*m).roll))[1] ) & 255;
    s[10] = (((unsigned char *)&((*m).roll))[2] ) & 255;
    s[11] = (((unsigned char *)&((*m).roll))[3] ) & 255;
#else
    s[0] = ((uint32_t)((*m).yaw)) & 255;
    s[1] = ((uint32_t)((*m).yaw)>> 8) & 255;
    s[2] = ((uint32_t)((*m).yaw)>> 16) & 255;
    s[3] = ((uint32_t)((*m).yaw)>> 24) & 255;
    s[4] = ((uint32_t)((*m).pitch)) & 255;
    s[5] = ((uint32_t)((*m).pitch)>> 8) & 255;
    s[6] = ((uint32_t)((*m).pitch)>> 16) & 255;
    s[7] = ((uint32_t)((*m).pitch)>> 24) & 255;
    s[8] = ((uint32_t)((*m).roll)) & 255;
    s[9] = ((uint32_t)((*m).roll)>> 8) & 255;
    s[10] = ((uint32_t)((*m).roll)>> 16) & 255;
    s[11] = ((uint32_t)((*m).roll)>> 24) & 255;
#endif
    return BYTES_LENGTH_POSE;
}

size_t DecodePose(struct Pose *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    ((unsigned char *)&((*m).yaw))[0] = (s[0] ) & 255;
    ((unsigned char *)&((*m).yaw))[1] = (s[1] ) & 255;
    ((unsigned char *)&((*m).yaw))[2] = (s[2] ) & 255;
    ((unsigned char *)&((*m).yaw))[3] = (s[3] ) & 255;
    ((unsigned char *)&((*m).pitch))[0] = (s[4] ) & 255;
    ((unsigned char *)&((*m).pitch))[1] = (s[5] ) & 255;
    ((unsigned char *)&((*m).pitch))[2] = (s[6] ) & 255;
    ((unsigned char *)&((*m).pitch))[3] = (s[7] ) & 255;
    ((unsigned char *)&((*m).roll))[0] = (s[8] ) & 255;
    ((unsigned char *)&((*m).roll))[1] = (s[9] ) & 255;
    ((unsigned char *)&((*m).roll))[2] = (s[10] ) & 255;
    ((unsigned char *)&((*m).roll))[3] = (s[11] ) & 255;
#else
    memset(m, 0, sizeof(*m));
    (*m).yaw |= (int32_t)(((unsigned)(s[0])) & 255);
    (*m).yaw |= (int32_t)((uint32_t)(((unsigned)(s[1])) & 255) << 8);
    (*m).yaw |= (int32_t)((uint32_t)(((unsigned)(s[2])) & 255) << 16);
    (*m).yaw |= (int32_t)((uint32_t)(((unsigned)(s[3])) & 255) << 24);
    (*m).pitch |= (int32_t)(((unsigned)(s[4])) & 255);
    (*m).pitch |= (int32_t)((uint32_t)(((unsigned)(s[5])) & 255) << 8);
    (*m).pitch |= (int32_t)((uint32_t)(((unsigned)(s[6])) & 255) << 16);
    (*m).pitch |= (int32_t)((uint32_t)(((unsigned)(s[7])) & 255) << 24);
    (*m).roll |= (int32_t)(((unsigned)(s[8])) & 255);
    (*m).roll |= (int32_t)((uint32_t)(((unsigned)(s[9])) & 255) << 8);
    (*m).roll |= (int32_t)((uint32_t)(((unsigned)(s[10])) & 255) << 16);
    (*m).roll |= (int32_t)((uint32_t)(((unsigned)(s[11])) & 255) << 24);
#endif
    return BYTES_LENGTH_POSE;
}

size_t EncodeFlight(struct Flight *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    s[0] = (((unsigned char *)&((*m).pose.yaw))[0] ) & 255;
    s[1] = (((unsigned char *)&((*m).pose.yaw))[1] ) & 255;
    s[2] = (((unsigned char *)&((*m).pose.yaw))[2] ) & 255;
    s[3] = (((unsigned char *)&((*m).pose.yaw))[3] ) & 255;
    s[4] = (((unsigned char *)&((*m).pose.pitch))[0] ) & 255;
    s[5] = (((unsigned char *)&((*m).pose.pitch))[1] ) & 255;
    s[6] = (((unsigned char *)&((*m).pose.pitch))[2] ) & 255;
    s[7] = (((unsigned char *)&((*m).pose.pitch))[3] ) & 255;
    s[8] = (((unsigned char *)&((*m).pose.roll))[0] ) & 255;
    s[9] = (((unsigned char *)&((*m).pose.roll))[1] ) & 255;
    s[10] = (((unsigned char *)&((*m).pose.roll))[2] ) & 255;
    s[11] = (((unsigned char *)&((*m).pose.roll))[3] ) & 255;
    s[12] = (((unsigned char *)&((*m).velocity[0]))[0] ) & 255;
    s[13] = (((unsigned char *)&((*m).velocity[0]))[1] ) & 255;
    s[14] = (((unsigned char *)&((*m).velocity[0]))[2] ) & 255;
    s[15] = (((unsigned char *)&((*m).velocity[0]))[3] ) & 255;
    s[16] = (((unsigned char *)&((*m).velocity[1]))[0] ) & 255;
    s[17] = (((unsigned char *)&((*m).velocity[1]))[1] ) & 255;
    s[18] = (((unsigned char *)&((*m).velocity[1]))[2] ) & 255;
    s[19] = (((unsigned char *)&((*m).velocity[1]))[3] ) & 255;
    s[20] = (((unsigned char *)&((*m).velocity[2]))[0] ) & 255;
    s[21] = (((unsigned char *)&((*m).velocity[2]))[1] ) & 255;
    s[22] = (((unsigned char *)&((*m).velocity[2]))[2] ) & 255;
    s[23] = (((unsigned char *)&((*m).velocity[2]))[3] ) & 255;
    s[24] = (((unsigned char *)&((*m).acceleration[0]))[0] ) & 255;
    s[25] = (((unsigned char *)&((*m).acceleration[0]))[1] ) & 255;
    s[26] = (((unsigned char *)&((*m).acceleration[0]))[2] ) & 255;
    s[27] = (((unsigned char *)&((*m).acceleration[0]))[3] ) & 255;
    s[28] = (((unsigned char *)&((*m).acceleration[1]))[0] ) & 255;
    s[29] = (((unsigned char *)&((*m).acceleration[1]))[1] ) & 255;
    s[30] = (((unsigned char *)&((*m).acceleration[1]))[2] ) & 255;
    s[31] = (((unsigned char *)&((*m).acceleration[1]))[3] ) & 255;
    s[32] = (((unsigned char *)&((*m).acceleration[2]))[0] ) & 255;
    s[33] = (((unsigned char *)&((*m).acceleration[2]))[1] ) & 255;
    s[34] = (((unsigned char *)&((*m).acceleration[2]))[2] ) & 255;
    s[35] = (((unsigned char *)&((*m).acceleration[2]))[3] ) & 255;
#else
    s[0] = ((uint32_t)((*m).pose.yaw)) & 255;
    s[1] = ((uint32_t)((*m).pose.yaw)>> 8) & 255;
    s[2] = ((uint32_t)((*m).pose.yaw)>> 16) & 255;
    s[3] = ((uint32_t)((*m).pose.yaw)>> 24) & 255;
    s[4] = ((uint32_t)((*m).pose.pitch)) & 255;
    s[5] = ((uint32_t)((*m).pose.pitch)>> 8) & 255;
    s[6] = ((uint32_t)((*m).pose.pitch)>> 16) & 255;
    s[7] = ((uint32_t)((*m).pose.pitch)>> 24) & 255;
    s[8] = ((uint32_t)((*m).pose.roll)) & 255;
    s[9] = ((uint32_t)((*m).pose.roll)>> 8) & 255;
    s[10] = ((uint32_t)((*m).pose.roll)>> 16) & 255;
    s[11] = ((uint32_t)((*m).pose.roll)>> 24) & 255;
    s[12] = ((uint32_t)((*m).velocity[0])) & 255;
    s[13] = ((uint32_t)((*m).velocity[0])>> 8) & 255;
    s[14] = ((uint32_t)((*m).velocity[0])>> 16) & 255;
    s[15] = ((uint32_t)((*m).velocity[0])>> 24) & 255;
    s[16] = ((uint32_t)((*m).velocity[1])) & 255;
    s[17] = ((uint32_t)((*m).velocity[1])>> 8) & 255;
    s[18] = ((uint32_t)((*m).velocity[1])>> 16) & 255;
    s[19] = ((uint32_t)((*m).velocity[1])>> 24) & 255;
    s[20] = ((uint32_t)((*m).velocity[2])) & 255;
    s[21] = ((uint32_t)((*m).velocity[2])>> 8) & 255;
    s[22] = ((uint32_t)((*m).velocity[2])>> 16) & 255;
    s[23] = ((uint32_t)((*m).velocity[2])>> 24) & 255;
    s[24] = ((uint32_t)((*m).acceleration[0])) & 255;
    s[25] = ((uint32_t)((*m).acceleration[0])>> 8) & 255;
    s[26] = ((uint32_t)((*m).acceleration[0])>> 16) & 255;
    s[27] = ((uint32_t)((*m).acceleration[0])>> 24) & 255;
    s[28] = ((uint32_t)((*m).acceleration[1])) & 255;
    s[29] = ((uint32_t)((*m).acceleration[1])>> 8) & 255;
    s[30] = ((uint32_t)((*m).acceleration[1])>> 16) & 255;
    s[31] = ((uint32_t)((*m).acceleration[1])>> 24) & 255;
    s[32] = ((uint32_t)((*m).acceleration[2])) & 255;
    s[33] = ((uint32_t)((*m).acceleration[2])>> 8) & 255;
    s[34] = ((uint32_t)((*m).acceleration[2])>> 16) & 255;
    s[35] = ((uint32_t)((*m).acceleration[2])>> 24) & 255;
#endif
    return BYTES_LENGTH_FLIGHT;
}

size_t DecodeFlight(struct Flight *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    ((unsigned char *)&((*m).pose.yaw))[0] = (s[0] ) & 255;
    ((unsigned char *)&((*m).pose.yaw))[1] = (s[1] ) & 255;
    ((unsigned char *)&((*m).pose.yaw))[2] = (s[2] ) & 255;
    ((unsigned char *)&((*m).pose.yaw))[3] = (s[3] ) & 255;
    ((unsigned char *)&((*m).pose.pitch))[0] = (s[4] ) & 255;
    ((unsigned char *)&((*m).pose.pitch))[1] = (s[5] ) & 255;
    ((unsigned char *)&((*m).pose.pitch))[2] = (s[6] ) & 255;
    ((unsigned char *)&((*m).pose.pitch))[3] = (s[7] ) & 255;
    ((unsigned char *)&((*m).pose.roll))[0] = (s[8] ) & 255;
    ((unsigned char *)&((*m).pose.roll))[1] = (s[9] ) & 255;
    ((unsigned char *)&((*m).pose.roll))[2] = (s[10] ) & 255;
    ((unsigned char *)&((*m).pose.roll))[3] = (s[11] ) & 255;
    ((unsigned char *)&((*m).velocity[0]))[0] = (s[12] ) & 255;
    ((unsigned char *)&((*m).velocity[0]))[1] = (s[13] ) & 255;
    ((unsigned char *)&((*m).velocity[0]))[2] = (s[14] ) & 255;
    ((unsigned char *)&((*m).velocity[0]))[3] = (s[15] ) & 255;
    ((unsigned char *)&((*m).velocity[1]))[0] = (s[16] ) & 255;
    ((unsigned char *)&((*m).velocity[1]))[1] = (s[17] ) & 255;
    ((unsigned char *)&((*m).velocity[1]))[2] = (s[18] ) & 255;
    ((unsigned char *)&((*m).velocity[1]))[3] = (s[19] ) & 255;
    ((unsigned char *)&((*m).velocity[2]))[0] = (s[20] ) & 255;
    ((unsigned char *)&((*m).velocity[2]))[1] = (s[21] ) & 255;
    ((unsigned char *)&((*m).velocity[2]))[2] = (s[22] ) & 255;
    ((unsigned char *)&((*m).velocity[2]))[3] = (s[23] ) & 255;
    ((unsigned char *)&((*m).acceleration[0]))[0] = (s[24] ) & 255;
    ((unsigned char *)&((*m).acceleration[0]))[1] = (s[25] ) & 255;
    ((unsigned char *)&((*m).acceleration[0]))[2] = (s[26] ) & 255;
    ((unsigned char *)&((*m).acceleration[0]))[3] = (s[27] ) & 255;
    ((unsigned char *)&((*m).acceleration[1]))[0] = (s[28] ) & 255;
    ((unsigned char *)&((*m).acceleration[1]))[1] = (s[29] ) & 255;
    ((unsigned char *)&((*m).acceleration[1]))[2] = (s[30] ) & 255;
    ((unsigned char *)&((*m).acceleration[1]))[3] = (s[31] ) & 255;
    ((unsigned char *)&((*m).acceleration[2]))[0] = (s[32] ) & 255;
    ((unsigned char *)&((*m).acceleration[2]))[1] = (s[33] ) & 255;
    ((unsigned char *)&((*m).acceleration[2]))[2] = (s[34] ) & 255;
    ((unsigned char *)&((*m).acceleration[2]))[3] = (s[35] ) & 255;
#else
    memset(m, 0, sizeof(*m));
    (*m).pose.yaw |= (int32_t)(((unsigned)(s[0])) & 255);
    (*m).pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[1])) & 255) << 8);
    (*m).pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[2])) & 255) << 16);
    (*m).pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[3])) & 255) << 24);
    (*m).pose.pitch |= (int32_t)(((unsigned)(s[4])) & 255);
    (*m).pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[5])) & 255) << 8);
    (*m).pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[6])) & 255) << 16);
    (*m).pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[7])) & 255) << 24);
    (*m).pose.roll |= (int32_t)(((unsigned)(s[8])) & 255);
    (*m).pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[9])) & 255) << 8);
    (*m).pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[10])) & 255) << 16);
    (*m).pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[11])) & 255) << 24);
    (*m).velocity[0] |= (int32_t)(((unsigned)(s[12])) & 255);
    (*m).velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[13])) & 255) << 8);
    (*m).velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[14])) & 255) << 16);
    (*m).velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[15])) & 255) << 24);
    (*m).velocity[1] |= (int32_t)(((unsigned)(s[16])) & 255);
    (*m).velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[17])) & 255) << 8);
    (*m).velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[18])) & 255) << 16);
    (*m).velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[19])) & 255) << 24);
    (*m).velocity[2] |= (int32_t)(((unsigned)(s[20])) & 255);
    (*m).velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[21])) & 255) << 8);
    (*m).velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[22])) & 255) << 16);
    (*m).velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[23])) & 255) << 24);
    (*m).acceleration[0] |= (int32_t)(((unsigned)(s[24])) & 255);
    (*m).acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[25])) & 255) << 8);
    (*m).acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[26])) & 255) << 16);
    (*m).acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[27])) & 255) << 24);
    (*m).acceleration[1] |= (int32_t)(((unsigned)(s[28])) & 255);
    (*m).acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[29])) & 255) << 8);
    (*m).acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[30])) & 255) << 16);
    (*m).acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[31])) & 255) << 24);
    (*m).acceleration[2] |= (int32_t)(((unsigned)(s[32])) & 255);
    (*m).acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[33])) & 255) << 8);
    (*m).acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[34])) & 255) << 16);
    (*m).acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[35])) & 255) << 24);
#endif
    return BYTES_LENGTH_FLIGHT;
}

size_t EncodeDrone(struct Drone *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    s[0] = (((unsigned char *)&((*m).status))[0] ) & 7;
    s[0] |= (((unsigned char *)&((*m).position.latitude))[0] << 3) & 248;
    s[1] = (((unsigned char *)&((*m).position.latitude))[0] >> 5) & 7;
    s[1] |= (((unsigned char *)&((*m).position.latitude))[1] << 3) & 248;
    s[2] = (((unsigned char *)&((*m).position.latitude))[1] >> 5) & 7;
    s[2] |= (((unsigned char *)&((*m).position.latitude))[2] << 3) & 248;
    s[3] = (((unsigned char *)&((*m).position.latitude))[2] >> 5) & 7;
    s[3] |= (((unsigned char *)&((*m).position.latitude))[3] << 3) & 248;
    s[4] = (((unsigned char *)&((*m).position.latitude))[3] >> 5) & 7;
    s[4] |= (((unsigned char *)&((*m).position.longitude))[0] << 3) & 248;
    s[5] = (((unsigned char *)&((*m).position.longitude))[0] >> 5) & 7;
    s[5] |= (((unsigned char *)&((*m).position.longitude))[1] << 3) & 248;
    s[6] = (((unsigned char *)&((*m).position.longitude))[1] >> 5) & 7;
    s[6] |= (((unsigned char *)&((*m).position.longitude))[2] << 3) & 248;
    s[7] = (((unsigned char *)&((*m).position.longitude))[2] >> 5) & 7;
    s[7] |= (((unsigned char *)&((*m).position.longitude))[3] << 3) & 248;
    s[8] = (((unsigned char *)&((*m).position.longitude))[3] >> 5) & 7;
    s[8] |= (((unsigned char *)&((*m).position.altitude))[0] << 3) & 248;
    s[9] = (((unsigned char *)&((*m).position.altitude))[0] >> 5) & 7;
    s[9] |= (((unsigned char *)&((*m).position.altitude))[1] << 3) & 248;
    s[10] = (((unsigned char *)&((*m).position.altitude))[1] >> 5) & 7;
    s[10] |= (((unsigned char *)&((*m).position.altitude))[2] << 3) & 248;
    s[11] = (((unsigned char *)&((*m).position.altitude))[2] >> 5) & 7;
    s[11] |= (((unsigned char *)&((*m).position.altitude))[3] << 3) & 248;
    s[12] = (((unsigned char *)&((*m).position.altitude))[3] >> 5) & 7;
    s[12] |= (((unsigned char *)&((*m).flight.pose.yaw))[0] << 3) & 248;
    s[13] = (((unsigned char *)&((*m).flight.pose.yaw))[0] >> 5) & 7;
    s[13] |= (((unsigned char *)&((*m).flight.pose.yaw))[1] << 3) & 248;
    s[14] = (((unsigned char *)&((*m).flight.pose.yaw))[1] >> 5) & 7;
    s[14] |= (((unsigned char *)&((*m).flight.pose.yaw))[2] << 3) & 248;
    s[15] = (((unsigned char *)&((*m).flight.pose.yaw))[2] >> 5) & 7;
    s[15] |= (((unsigned char *)&((*m).flight.pose.yaw))[3] << 3) & 248;
    s[16] = (((unsigned char *)&((*m).flight.pose.yaw))[3] >> 5) & 7;
    s[16] |= (((unsigned char *)&((*m).flight.pose.pitch))[0] << 3) & 248;
    s[17] = (((unsigned char *)&((*m).flight.pose.pitch))[0] >> 5) & 7;
    s[17] |= (((unsigned char *)&((*m).flight.pose.pitch))[1] << 3) & 248;
    s[18] = (((unsigned char *)&((*m).flight.pose.pitch))[1] >> 5) & 7;
    s[18] |= (((unsigned char *)&((*m).flight.pose.pitch))[2] << 3) & 248;
    s[19] = (((unsigned char *)&((*m).flight.pose.pitch))[2] >> 5) & 7;
    s[19] |= (((unsigned char *)&((*m).flight.pose.pitch))[3] << 3) & 248;
    s[20] = (((unsigned char *)&((*m).flight.pose.pitch))[3] >> 5) & 7;
    s[20] |= (((unsigned char *)&((*m).flight.pose.roll))[0] << 3) & 248;
    s[21] = (((unsigned char *)&((*m).flight.pose.roll))[0] >> 5) & 7;
    s[21] |= (((unsigned char *)&((*m).flight.pose.roll))[1] << 3) & 248;
    s[22] = (((unsigned char *)&((*m).flight.pose.roll))[1] >> 5) & 7;
    s[22] |= (((unsigned char *)&((*m).flight.pose.roll))[2] << 3) & 248;
    s[23] = (((unsigned char *)&((*m).flight.pose.roll))[2] >> 5) & 7;
    s[23] |= (((unsigned char *)&((*m).flight.pose.roll))[3] << 3) & 248;
    s[24] = (((unsigned char *)&((*m).flight.pose.roll))[3] >> 5) & 7;
    s[24] |= (((unsigned char *)&((*m).flight.velocity[0]))[0] << 3) & 248;
    s[25] = (((unsigned char *)&((*m).flight.velocity[0]))[0] >> 5) & 7;
    s[25] |= (((unsigned char *)&((*m).flight.velocity[0]))[1] << 3) & 248;
    s[26] = (((unsigned char *)&((*m).flight.velocity[0]))[1] >> 5) & 7;
    s[26] |= (((unsigned char *)&((*m).flight.velocity[0]))[2] << 3) & 248;
    s[27] = (((unsigned char *)&((*m).flight.velocity[0]))[2] >> 5) & 7;
    s[27] |= (((unsigned char *)&((*m).flight.velocity[0]))[3] << 3) & 248;
    s[28] = (((unsigned char *)&((*m).flight.velocity[0]))[3] >> 5) & 7;
    s[28] |= (((unsigned char *)&((*m).flight.velocity[1]))[0] << 3) & 248;
    s[29] = (((unsigned char *)&((*m).flight.velocity[1]))[0] >> 5) & 7;
    s[29] |= (((unsigned char *)&((*m).flight.velocity[1]))[1] << 3) & 248;
    s[30] = (((unsigned char *)&((*m).flight.velocity[1]))[1] >> 5) & 7;
    s[30] |= (((unsigned char *)&((*m).flight.velocity[1]))[2] << 3) & 248;
    s[31] = (((unsigned char *)&((*m).flight.velocity[1]))[2] >> 5) & 7;
    s[31] |= (((unsigned char *)&((*m).flight.velocity[1]))[3] << 3) & 248;
    s[32] = (((unsigned char *)&((*m).flight.velocity[1]))[3] >> 5) & 7;
    s[32] |= (((unsigned char *)&((*m).flight.velocity[2]))[0] << 3) & 248;
    s[33] = (((unsigned char *)&((*m).flight.velocity[2]))[0] >> 5) & 7;
    s[33] |= (((unsigned char *)&((*m).flight.velocity[2]))[1] << 3) & 248;
    s[34] = (((unsigned char *)&((*m).flight.velocity[2]))[1] >> 5) & 7;
    s[34] |= (((unsigned char *)&((*m).flight.velocity[2]))[2] << 3) & 248;
    s[35] = (((unsigned char *)&((*m).flight.velocity[2]))[2] >> 5) & 7;
    s[35] |= (((unsigned char *)&((*m).flight.velocity[2]))[3] << 3) & 248;
    s[36] = (((unsigned char *)&((*m).flight.velocity[2]))[3] >> 5) & 7;
    s[36] |= (((unsigned char *)&((*m).flight.acceleration[0]))[0] << 3) & 248;
    s[37] = (((unsigned char *)&((*m).flight.acceleration[0]))[0] >> 5) & 7;
    s[37] |= (((unsigned char *)&((*m).flight.acceleration[0]))[1] << 3) & 248;
    s[38] = (((unsigned char *)&((*m).flight.acceleration[0]))[1] >> 5) & 7;
    s[38] |= (((unsigned char *)&((*m).flight.acceleration[0]))[2] << 3) & 248;
    s[39] = (((unsigned char *)&((*m).flight.acceleration[0]))[2] >> 5) & 7;
    s[39] |= (((unsigned char *)&((*m).flight.acceleration[0]))[3] << 3) & 248;
    s[40] = (((unsigned char *)&((*m).flight.acceleration[0]))[3] >> 5) & 7;
    s[40] |= (((unsigned char *)&((*m).flight.acceleration[1]))[0] << 3) & 248;
    s[41] = (((unsigned char *)&((*m).flight.acceleration[1]))[0] >> 5) & 7;
    s[41] |= (((unsigned char *)&((*m).flight.acceleration[1]))[1] << 3) & 248;
    s[42] = (((unsigned char *)&((*m).flight.acceleration[1]))[1] >> 5) & 7;
    s[42] |= (((unsigned char *)&((*m).flight.acceleration[1]))[2] << 3) & 248;
    s[43] = (((unsigned char *)&((*m).flight.acceleration[1]))[2] >> 5) & 7;
    s[43] |= (((unsigned char *)&((*m).flight.acceleration[1]))[3] << 3) & 248;
    s[44] = (((unsigned char *)&((*m).flight.acceleration[1]))[3] >> 5) & 7;
    s[44] |= (((unsigned char *)&((*m).flight.acceleration[2]))[0] << 3) & 248;
    s[45] = (((unsigned char *)&((*m).flight.acceleration[2]))[0] >> 5) & 7;
    s[45] |= (((unsigned char *)&((*m).flight.acceleration[2]))[1] << 3) & 248;
    s[46] = (((unsigned char *)&((*m).flight.acceleration[2]))[1] >> 5) & 7;
    s[46] |= (((unsigned char *)&((*m).flight.acceleration[2]))[2] << 3) & 248;
    s[47] = (((unsigned char *)&((*m).flight.acceleration[2]))[2] >> 5) & 7;
    s[47] |= (((unsigned char *)&((*m).flight.acceleration[2]))[3] << 3) & 248;
    s[48] = (((unsigned char *)&((*m).flight.acceleration[2]))[3] >> 5) & 7;
    s[48] |= (((unsigned char *)&((*m).propellers[0].id))[0] << 3) & 248;
    s[49] = (((unsigned char *)&((*m).propellers[0].id))[0] >> 5) & 7;
    s[49] |= (((unsigned char *)&((*m).propellers[0].status))[0] << 3) & 24;
    s[49] |= (((unsigned char *)&((*m).propellers[0].direction))[0] << 5) & 96;
    s[49] |= (((unsigned char *)&((*m).propellers[1].id))[0] << 7) & 128;
    s[50] = (((unsigned char *)&((*m).propellers[1].id))[0] >> 1) & 127;
    s[50] |= (((unsigned char *)&((*m).propellers[1].status))[0] << 7) & 128;
    s[51] = (((unsigned char *)&((*m).propellers[1].status))[0] >> 1) & 1;
    s[51] |= (((unsigned char *)&((*m).propellers[1].direction))[0] << 1) & 6;
    s[51] |= (((unsigned char *)&((*m).propellers[2].id))[0] << 3) & 248;
    s[52] = (((unsigned char *)&((*m).propellers[2].id))[0] >> 5) & 7;
    s[52] |= (((unsigned char *)&((*m).propellers[2].status))[0] << 3) & 24;
    s[52] |= (((unsigned char *)&((*m).propellers[2].direction))[0] << 5) & 96;
    s[52] |= (((unsigned char *)&((*m).propellers[3].id))[0] << 7) & 128;
    s[53] = (((unsigned char *)&((*m).propellers[3].id))[0] >> 1) & 127;
    s[53] |= (((unsigned char *)&((*m).propellers[3].status))[0] << 7) & 128;
    s[54] = (((unsigned char *)&((*m).propellers[3].status))[0] >> 1) & 1;
    s[54] |= (((unsigned char *)&((*m).propellers[3].direction))[0] << 1) & 6;
    s[54] |= (((unsigned char *)&((*m).power.battery))[0] << 3) & 248;
    s[55] = (((unsigned char *)&((*m).power.battery))[0] >> 5) & 7;
    s[55] |= (((unsigned char *)&((*m).power.status))[0] << 3) & 24;
    s[55] |= (((unsigned char *)&((*m).power.is_charging))[0] << 5) & 32;
    s[55] |= (((unsigned char *)&((*m).network.signal))[0] << 6) & 192;
    s[56] = (((unsigned char *)&((*m).network.signal))[0] >> 2) & 3;
    s[56] |= (((unsigned char *)&((*m).network.heartbeat_at))[0] << 2) & 252;
    s[57] = (((unsigned char *)&((*m).network.heartbeat_at))[0] >> 6) & 3;
    s[57] |= (((unsigned char *)&((*m).network.heartbeat_at))[1] << 2) & 252;
    s[58] = (((unsigned char *)&((*m).network.heartbeat_at))[1] >> 6) & 3;
    s[58] |= (((unsigned char *)&((*m).network.heartbeat_at))[2] << 2) & 252;
    s[59] = (((unsigned char *)&((*m).network.heartbeat_at))[2] >> 6) & 3;
    s[59] |= (((unsigned char *)&((*m).network.heartbeat_at))[3] << 2) & 252;
    s[60] = (((unsigned char *)&((*m).network.heartbeat_at))[3] >> 6) & 3;
    s[60] |= (((unsigned char *)&((*m).network.heartbeat_at))[4] << 2) & 252;
    s[61] = (((unsigned char *)&((*m).network.heartbeat_at))[4] >> 6) & 3;
    s[61] |= (((unsigned char *)&((*m).network.heartbeat_at))[5] << 2) & 252;
    s[62] = (((unsigned char *)&((*m).network.heartbeat_at))[5] >> 6) & 3;
    s[62] |= (((unsigned char *)&((*m).network.heartbeat_at))[6] << 2) & 252;
    s[63] = (((unsigned char *)&((*m).network.heartbeat_at))[6] >> 6) & 3;
    s[63] |= (((unsigned char *)&((*m).network.heartbeat_at))[7] << 2) & 252;
    s[64] = (((unsigned char *)&((*m).network.heartbeat_at))[7] >> 6) & 3;
    s[64] |= (((unsigned char *)&((*m).landing_gear.status))[0] << 2) & 12;
#else
    s[0] = ((uint8_t)((*m).status)) & 7;
    s[0] |= ((uint32_t)((*m).position.latitude)<< 3) & 248;
    s[1] = ((uint32_t)((*m).position.latitude)>> 5) & 7;
    s[1] |= ((uint32_t)((*m).position.latitude)>> 5) & 248;
    s[2] = ((uint32_t)((*m).position.latitude)>> 13) & 7;
    s[2] |= ((uint32_t)((*m).position.latitude)>> 13) & 248;
    s[3] = ((uint32_t)((*m).position.latitude)>> 21) & 7;
    s[3] |= ((uint32_t)((*m).position.latitude)>> 21) & 248;
    s[4] = ((uint32_t)((*m).position.latitude)>> 29) & 7;
    s[4] |= ((uint32_t)((*m).position.longitude)<< 3) & 248;
    s[5] = ((uint32_t)((*m).position.longitude)>> 5) & 7;
    s[5] |= ((uint32_t)((*m).position.longitude)>> 5) & 248;
    s[6] = ((uint32_t)((*m).position.longitude)>> 13) & 7;
    s[6] |= ((uint32_t)((*m).position.longitude)>> 13) & 248;
    s[7] = ((uint32_t)((*m).position.longitude)>> 21) & 7;
    s[7] |= ((uint32_t)((*m).position.longitude)>> 21) & 248;
    s[8] = ((uint32_t)((*m).position.longitude)>> 29) & 7;
    s[8] |= ((uint32_t)((*m).position.altitude)<< 3) & 248;
    s[9] = ((uint32_t)((*m).position.altitude)>> 5) & 7;
    s[9] |= ((uint32_t)((*m).position.altitude)>> 5) & 248;
    s[10] = ((uint32_t)((*m).position.altitude)>> 13) & 7;
    s[10] |= ((uint32_t)((*m).position.altitude)>> 13) & 248;
    s[11] = ((uint32_t)((*m).position.altitude)>> 21) & 7;
    s[11] |= ((uint32_t)((*m).position.altitude)>> 21) & 248;
    s[12] = ((uint32_t)((*m).position.altitude)>> 29) & 7;
    s[12] |= ((uint32_t)((*m).flight.pose.yaw)<< 3) & 248;
    s[13] = ((uint32_t)((*m).flight.pose.yaw)>> 5) & 7;
    s[13] |= ((uint32_t)((*m).flight.pose.yaw)>> 5) & 248;
    s[14] = ((uint32_t)((*m).flight.pose.yaw)>> 13) & 7;
    s[14] |= ((uint32_t)((*m).flight.pose.yaw)>> 13) & 248;
    s[15] = ((uint32_t)((*m).flight.pose.yaw)>> 21) & 7;
    s[15] |= ((uint32_t)((*m).flight.pose.yaw)>> 21) & 248;
    s[16] = ((uint32_t)((*m).flight.pose.yaw)>> 29) & 7;
    s[16] |= ((uint32_t)((*m).flight.pose.pitch)<< 3) & 248;
    s[17] = ((uint32_t)((*m).flight.pose.pitch)>> 5) & 7;
    s[17] |= ((uint32_t)((*m).flight.pose.pitch)>> 5) & 248;
    s[18] = ((uint32_t)((*m).flight.pose.pitch)>> 13) & 7;
    s[18] |= ((uint32_t)((*m).flight.pose.pitch)>> 13) & 248;
    s[19] = ((uint32_t)((*m).flight.pose.pitch)>> 21) & 7;
    s[19] |= ((uint32_t)((*m).flight.pose.pitch)>> 21) & 248;
    s[20] = ((uint32_t)((*m).flight.pose.pitch)>> 29) & 7;
    s[20] |= ((uint32_t)((*m).flight.pose.roll)<< 3) & 248;
    s[21] = ((uint32_t)((*m).flight.pose.roll)>> 5) & 7;
    s[21] |= ((uint32_t)((*m).flight.pose.roll)>> 5) & 248;
    s[22] = ((uint32_t)((*m).flight.pose.roll)>> 13) & 7;
    s[22] |= ((uint32_t)((*m).flight.pose.roll)>> 13) & 248;
    s[23] = ((uint32_t)((*m).flight.pose.roll)>> 21) & 7;
    s[23] |= ((uint32_t)((*m).flight.pose.roll)>> 21) & 248;
    s[24] = ((uint32_t)((*m).flight.pose.roll)>> 29) & 7;
    s[24] |= ((uint32_t)((*m).flight.velocity[0])<< 3) & 248;
    s[25] = ((uint32_t)((*m).flight.velocity[0])>> 5) & 7;
    s[25] |= ((uint32_t)((*m).flight.velocity[0])>> 5) & 248;
    s[26] = ((uint32_t)((*m).flight.velocity[0])>> 13) & 7;
    s[26] |= ((uint32_t)((*m).flight.velocity[0])>> 13) & 248;
    s[27] = ((uint32_t)((*m).flight.velocity[0])>> 21) & 7;
    s[27] |= ((uint32_t)((*m).flight.velocity[0])>> 21) & 248;
    s[28] = ((uint32_t)((*m).flight.velocity[0])>> 29) & 7;
    s[28] |= ((uint32_t)((*m).flight.velocity[1])<< 3) & 248;
    s[29] = ((uint32_t)((*m).flight.velocity[1])>> 5) & 7;
    s[29] |= ((uint32_t)((*m).flight.velocity[1])>> 5) & 248;
    s[30] = ((uint32_t)((*m).flight.velocity[1])>> 13) & 7;
    s[30] |= ((uint32_t)((*m).flight.velocity[1])>> 13) & 248;
    s[31] = ((uint32_t)((*m).flight.velocity[1])>> 21) & 7;
    s[31] |= ((uint32_t)((*m).flight.velocity[1])>> 21) & 248;
    s[32] = ((uint32_t)((*m).flight.velocity[1])>> 29) & 7;
    s[32] |= ((uint32_t)((*m).flight.velocity[2])<< 3) & 248;
    s[33] = ((uint32_t)((*m).flight.velocity[2])>> 5) & 7;
    s[33] |= ((uint32_t)((*m).flight.velocity[2])>> 5) & 248;
    s[34] = ((uint32_t)((*m).flight.velocity[2])>> 13) & 7;
    s[34] |= ((uint32_t)((*m).flight.velocity[2])>> 13) & 248;
    s[35] = ((uint32_t)((*m).flight.velocity[2])>> 21) & 7;
    s[35] |= ((uint32_t)((*m).flight.velocity[2])>> 21) & 248;
    s[36] = ((uint32_t)((*m).flight.velocity[2])>> 29) & 7;
    s[36] |= ((uint32_t)((*m).flight.acceleration[0])<< 3) & 248;
    s[37] = ((uint32_t)((*m).flight.acceleration[0])>> 5) & 7;
    s[37] |= ((uint32_t)((*m).flight.acceleration[0])>> 5) & 248;
    s[38] = ((uint32_t)((*m).flight.acceleration[0])>> 13) & 7;
    s[38] |= ((uint32_t)((*m).flight.acceleration[0])>> 13) & 248;
    s[39] = ((uint32_t)((*m).flight.acceleration[0])>> 21) & 7;
    s[39] |= ((uint32_t)((*m).flight.acceleration[0])>> 21) & 248;
    s[40] = ((uint32_t)((*m).flight.acceleration[0])>> 29) & 7;
    s[40] |= ((uint32_t)((*m).flight.acceleration[1])<< 3) & 248;
    s[41] = ((uint32_t)((*m).flight.acceleration[1])>> 5) & 7;
    s[41] |= ((uint32_t)((*m).flight.acceleration[1])>> 5) & 248;
    s[42] = ((uint32_t)((*m).flight.acceleration[1])>> 13) & 7;
    s[42] |= ((uint32_t)((*m).flight.acceleration[1])>> 13) & 248;
    s[43] = ((uint32_t)((*m).flight.acceleration[1])>> 21) & 7;
    s[43] |= ((uint32_t)((*m).flight.acceleration[1])>> 21) & 248;
    s[44] = ((uint32_t)((*m).flight.acceleration[1])>> 29) & 7;
    s[44] |= ((uint32_t)((*m).flight.acceleration[2])<< 3) & 248;
    s[45] = ((uint32_t)((*m).flight.acceleration[2])>> 5) & 7;
    s[45] |= ((uint32_t)((*m).flight.acceleration[2])>> 5) & 248;
    s[46] = ((uint32_t)((*m).flight.acceleration[2])>> 13) & 7;
    s[46] |= ((uint32_t)((*m).flight.acceleration[2])>> 13) & 248;
    s[47] = ((uint32_t)((*m).flight.acceleration[2])>> 21) & 7;
    s[47] |= ((uint32_t)((*m).flight.acceleration[2])>> 21) & 248;
    s[48] = ((uint32_t)((*m).flight.acceleration[2])>> 29) & 7;
    s[48] |= ((uint8_t)((*m).propellers[0].id)<< 3) & 248;
    s[49] = ((uint8_t)((*m).propellers[0].id)>> 5) & 7;
    s[49] |= ((uint8_t)((*m).propellers[0].status)<< 3) & 24;
    s[49] |= ((uint8_t)((*m).propellers[0].direction)<< 5) & 96;
    s[49] |= ((uint8_t)((*m).propellers[1].id)<< 7) & 128;
    s[50] = ((uint8_t)((*m).propellers[1].id)>> 1) & 127;
    s[50] |= ((uint8_t)((*m).propellers[1].status)<< 7) & 128;
    s[51] = ((uint8_t)((*m).propellers[1].status)>> 1) & 1;
    s[51] |= ((uint8_t)((*m).propellers[1].direction)<< 1) & 6;
    s[51] |= ((uint8_t)((*m).propellers[2].id)<< 3) & 248;
    s[52] = ((uint8_t)((*m).propellers[2].id)>> 5) & 7;
    s[52] |= ((uint8_t)((*m).propellers[2].status)<< 3) & 24;
    s[52] |= ((uint8_t)((*m).propellers[2].direction)<< 5) & 96;
    s[52] |= ((uint8_t)((*m).propellers[3].id)<< 7) & 128;
    s[53] = ((uint8_t)((*m).propellers[3].id)>> 1) & 127;
    s[53] |= ((uint8_t)((*m).propellers[3].status)<< 7) & 128;
    s[54] = ((uint8_t)((*m).propellers[3].status)>> 1) & 1;
    s[54] |= ((uint8_t)((*m).propellers[3].direction)<< 1) & 6;
    s[54] |= ((uint8_t)((*m).power.battery)<< 3) & 248;
    s[55] = ((uint8_t)((*m).power.battery)>> 5) & 7;
    s[55] |= ((uint8_t)((*m).power.status)<< 3) & 24;
    s[55] |= ((uint8_t)((*m).power.is_charging)<< 5) & 32;
    s[55] |= ((uint8_t)((*m).network.signal)<< 6) & 192;
    s[56] = ((uint8_t)((*m).network.signal)>> 2) & 3;
    s[56] |= ((uint64_t)((*m).network.heartbeat_at)<< 2) & 252;
    s[57] = ((uint64_t)((*m).network.heartbeat_at)>> 6) & 3;
    s[57] |= ((uint64_t)((*m).network.heartbeat_at)>> 6) & 252;
    s[58] = ((uint64_t)((*m).network.heartbeat_at)>> 14) & 3;
    s[58] |= ((uint64_t)((*m).network.heartbeat_at)>> 14) & 252;
    s[59] = ((uint64_t)((*m).network.heartbeat_at)>> 22) & 3;
    s[59] |= ((uint64_t)((*m).network.heartbeat_at)>> 22) & 252;
    s[60] = ((uint64_t)((*m).network.heartbeat_at)>> 30) & 3;
    s[60] |= ((uint64_t)((*m).network.heartbeat_at)>> 30) & 252;
    s[61] = ((uint64_t)((*m).network.heartbeat_at)>> 38) & 3;
    s[61] |= ((uint64_t)((*m).network.heartbeat_at)>> 38) & 252;
    s[62] = ((uint64_t)((*m).network.heartbeat_at)>> 46) & 3;
    s[62] |= ((uint64_t)((*m).network.heartbeat_at)>> 46) & 252;
    s[63] = ((uint64_t)((*m).network.heartbeat_at)>> 54) & 3;
    s[63] |= ((uint64_t)((*m).network.heartbeat_at)>> 54) & 252;
    s[64] = ((uint64_t)((*m).network.heartbeat_at)>> 62) & 3;
    s[64] |= ((uint8_t)((*m).landing_gear.status)<< 2) & 12;
#endif
    return BYTES_LENGTH_DRONE;
}

size_t DecodeDrone(struct Drone *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    ((unsigned char *)&((*m).status))[0] = (s[0] ) & 7;
    ((unsigned char *)&((*m).position.latitude))[0] = (s[0] >> 3) & 31;
    ((unsigned char *)&((*m).position.latitude))[0] |= (s[1] << 5) & 224;
    ((unsigned char *)&((*m).position.latitude))[1] = (s[1] >> 3) & 31;
    ((unsigned char *)&((*m).position.latitude))[1] |= (s[2] << 5) & 224;
    ((unsigned char *)&((*m).position.latitude))[2] = (s[2] >> 3) & 31;
    ((unsigned char *)&((*m).position.latitude))[2] |= (s[3] << 5) & 224;
    ((unsigned char *)&((*m).position.latitude))[3] = (s[3] >> 3) & 31;
    ((unsigned char *)&((*m).position.latitude))[3] |= (s[4] << 5) & 224;
    ((unsigned char *)&((*m).position.longitude))[0] = (s[4] >> 3) & 31;
    ((unsigned char *)&((*m).position.longitude))[0] |= (s[5] << 5) & 224;
    ((unsigned char *)&((*m).position.longitude))[1] = (s[5] >> 3) & 31;
    ((unsigned char *)&((*m).position.longitude))[1] |= (s[6] << 5) & 224;
    ((unsigned char *)&((*m).position.longitude))[2] = (s[6] >> 3) & 31;
    ((unsigned char *)&((*m).position.longitude))[2] |= (s[7] << 5) & 224;
    ((unsigned char *)&((*m).position.longitude))[3] = (s[7] >> 3) & 31;
    ((unsigned char *)&((*m).position.longitude))[3] |= (s[8] << 5) & 224;
    ((unsigned char *)&((*m).position.altitude))[0] = (s[8] >> 3) & 31;
    ((unsigned char *)&((*m).position.altitude))[0] |= (s[9] << 5) & 224;
    ((unsigned char *)&((*m).position.altitude))[1] = (s[9] >> 3) & 31;
    ((unsigned char *)&((*m).position.altitude))[1] |= (s[10] << 5) & 224;
    ((unsigned char *)&((*m).position.altitude))[2] = (s[10] >> 3) & 31;
    ((unsigned char *)&((*m).position.altitude))[2] |= (s[11] << 5) & 224;
    ((unsigned char *)&((*m).position.altitude))[3] = (s[11] >> 3) & 31;
    ((unsigned char *)&((*m).position.altitude))[3] |= (s[12] << 5) & 224;
    ((unsigned char *)&((*m).flight.pose.yaw))[0] = (s[12] >> 3) & 31;
    ((unsigned char *)&((*m).flight.pose.yaw))[0] |= (s[13] << 5) & 224;
    ((unsigned char *)&((*m).flight.pose.yaw))[1] = (s[13] >> 3) & 31;
    ((unsigned char *)&((*m).flight.pose.yaw))[1] |= (s[14] << 5) & 224;
    ((unsigned char *)&((*m).flight.pose.yaw))[2] = (s[14] >> 3) & 31;
    ((unsigned char *)&((*m).flight.pose.yaw))[2] |= (s[15] << 5) & 224;
    ((unsigned char *)&((*m).flight.pose.yaw))[3] = (s[15] >> 3) & 31;
    ((unsigned char *)&((*m).flight.pose.yaw))[3] |= (s[16] << 5) & 224;
    ((unsigned char *)&((*m).flight.pose.pitch))[0] = (s[16] >> 3) & 31;
    ((unsigned char *)&((*m).flight.pose.pitch))[0] |= (s[17] << 5) & 224;
    ((unsigned char *)&((*m).flight.pose.pitch))[1] = (s[17] >> 3) & 31;
    ((unsigned char *)&((*m).flight.pose.pitch))[1] |= (s[18] << 5) & 224;
    ((unsigned char *)&((*m).flight.pose.pitch))[2] = (s[18] >> 3) & 31;
    ((unsigned char *)&((*m).flight.pose.pitch))[2] |= (s[19] << 5) & 224;
    ((unsigned char *)&((*m).flight.pose.pitch))[3] = (s[19] >> 3) & 31;
    ((unsigned char *)&((*m).flight.pose.pitch))[3] |= (s[20] << 5) & 224;
    ((unsigned char *)&((*m).flight.pose.roll))[0] = (s[20] >> 3) & 31;
    ((unsigned char *)&((*m).flight.pose.roll))[0] |= (s[21] << 5) & 224;
    ((unsigned char *)&((*m).flight.pose.roll))[1] = (s[21] >> 3) & 31;
    ((unsigned char *)&((*m).flight.pose.roll))[1] |= (s[22] << 5) & 224;
    ((unsigned char *)&((*m).flight.pose.roll))[2] = (s[22] >> 3) & 31;
    ((unsigned char *)&((*m).flight.pose.roll))[2] |= (s[23] << 5) & 224;
    ((unsigned char *)&((*m).flight.pose.roll))[3] = (s[23] >> 3) & 31;
    ((unsigned char *)&((*m).flight.pose.roll))[3] |= (s[24] << 5) & 224;
    ((unsigned char *)&((*m).flight.velocity[0]))[0] = (s[24] >> 3) & 31;
    ((unsigned char *)&((*m).flight.velocity[0]))[0] |= (s[25] << 5) & 224;
    ((unsigned char *)&((*m).flight.velocity[0]))[1] = (s[25] >> 3) & 31;
    ((unsigned char *)&((*m).flight.velocity[0]))[1] |= (s[26] << 5) & 224;
    ((unsigned char *)&((*m).flight.velocity[0]))[2] = (s[26] >> 3) & 31;
    ((unsigned char *)&((*m).flight.velocity[0]))[2] |= (s[27] << 5) & 224;
    ((unsigned char *)&((*m).flight.velocity[0]))[3] = (s[27] >> 3) & 31;
    ((unsigned char *)&((*m).flight.velocity[0]))[3] |= (s[28] << 5) & 224;
    ((unsigned char *)&((*m).flight.velocity[1]))[0] = (s[28] >> 3) & 31;
    ((unsigned char *)&((*m).flight.velocity[1]))[0] |= (s[29] << 5) & 224;
    ((unsigned char *)&((*m).flight.velocity[1]))[1] = (s[29] >> 3) & 31;
    ((unsigned char *)&((*m).flight.velocity[1]))[1] |= (s[30] << 5) & 224;
    ((unsigned char *)&((*m).flight.velocity[1]))[2] = (s[30] >> 3) & 31;
    ((unsigned char *)&((*m).flight.velocity[1]))[2] |= (s[31] << 5) & 224;
    ((unsigned char *)&((*m).flight.velocity[1]))[3] = (s[31] >> 3) & 31;
    ((unsigned char *)&((*m).flight.velocity[1]))[3] |= (s[32] << 5) & 224;
    ((unsigned char *)&((*m).flight.velocity[2]))[0] = (s[32] >> 3) & 31;
    ((unsigned char *)&((*m).flight.velocity[2]))[0] |= (s[33] << 5) & 224;
    ((unsigned char *)&((*m).flight.velocity[2]))[1] = (s[33] >> 3) & 31;
    ((unsigned char *)&((*m).flight.velocity[2]))[1] |= (s[34] << 5) & 224;
    ((unsigned char *)&((*m).flight.velocity[2]))[2] = (s[34] >> 3) & 31;
    ((unsigned char *)&((*m).flight.velocity[2]))[2] |= (s[35] << 5) & 224;
    ((unsigned char *)&((*m).flight.velocity[2]))[3] = (s[35] >> 3) & 31;
    ((unsigned char *)&((*m).flight.velocity[2]))[3] |= (s[36] << 5) & 224;
    ((unsigned char *)&((*m).flight.acceleration[0]))[0] = (s[36] >> 3) & 31;
    ((unsigned char *)&((*m).flight.acceleration[0]))[0] |= (s[37] << 5) & 224;
    ((unsigned char *)&((*m).flight.acceleration[0]))[1] = (s[37] >> 3) & 31;
    ((unsigned char *)&((*m).flight.acceleration[0]))[1] |= (s[38] << 5) & 224;
    ((unsigned char *)&((*m).flight.acceleration[0]))[2] = (s[38] >> 3) & 31;
    ((unsigned char *)&((*m).flight.acceleration[0]))[2] |= (s[39] << 5) & 224;
    ((unsigned char *)&((*m).flight.acceleration[0]))[3] = (s[39] >> 3) & 31;
    ((unsigned char *)&((*m).flight.acceleration[0]))[3] |= (s[40] << 5) & 224;
    ((unsigned char *)&((*m).flight.acceleration[1]))[0] = (s[40] >> 3) & 31;
    ((unsigned char *)&((*m).flight.acceleration[1]))[0] |= (s[41] << 5) & 224;
    ((unsigned char *)&((*m).flight.acceleration[1]))[1] = (s[41] >> 3) & 31;
    ((unsigned char *)&((*m).flight.acceleration[1]))[1] |= (s[42] << 5) & 224;
    ((unsigned char *)&((*m).flight.acceleration[1]))[2] = (s[42] >> 3) & 31;
    ((unsigned char *)&((*m).flight.acceleration[1]))[2] |= (s[43] << 5) & 224;
    ((unsigned char *)&((*m).flight.acceleration[1]))[3] = (s[43] >> 3) & 31;
    ((unsigned char *)&((*m).flight.acceleration[1]))[3] |= (s[44] << 5) & 224;
    ((unsigned char *)&((*m).flight.acceleration[2]))[0] = (s[44] >> 3) & 31;
    ((unsigned char *)&((*m).flight.acceleration[2]))[0] |= (s[45] << 5) & 224;
    ((unsigned char *)&((*m).flight.acceleration[2]))[1] = (s[45] >> 3) & 31;
    ((unsigned char *)&((*m).flight.acceleration[2]))[1] |= (s[46] << 5) & 224;
    ((unsigned char *)&((*m).flight.acceleration[2]))[2] = (s[46] >> 3) & 31;
    ((unsigned char *)&((*m).flight.acceleration[2]))[2] |= (s[47] << 5) & 224;
    ((unsigned char *)&((*m).flight.acceleration[2]))[3] = (s[47] >> 3) & 31;
    ((unsigned char *)&((*m).flight.acceleration[2]))[3] |= (s[48] << 5) & 224;
    ((unsigned char *)&((*m).propellers[0].id))[0] = (s[48] >> 3) & 31;
    ((unsigned char *)&((*m).propellers[0].id))[0] |= (s[49] << 5) & 224;
    ((unsigned char *)&((*m).propellers[0].status))[0] = (s[49] >> 3) & 3;
    ((unsigned char *)&((*m).propellers[0].direction))[0] = (s[49] >> 5) & 3;
    ((unsigned char *)&((*m).propellers[1].id))[0] = (s[49] >> 7) & 1;
    ((unsigned char *)&((*m).propellers[1].id))[0] |= (s[50] << 1) & 254;
    ((unsigned char *)&((*m).propellers[1].status))[0] = (s[50] >> 7) & 1;
    ((unsigned char *)&((*m).propellers[1].status))[0] |= (s[51] << 1) & 2;
    ((unsigned char *)&((*m).propellers[1].direction))[0] = (s[51] >> 1) & 3;
    ((unsigned char *)&((*m).propellers[2].id))[0] = (s[51] >> 3) & 31;
    ((unsigned char *)&((*m).propellers[2].id))[0] |= (s[52] << 5) & 224;
    ((unsigned char *)&((*m).propellers[2].status))[0] = (s[52] >> 3) & 3;
    ((unsigned char *)&((*m).propellers[2].direction))[0] = (s[52] >> 5) & 3;
    ((unsigned char *)&((*m).propellers[3].id))[0] = (s[52] >> 7) & 1;
    ((unsigned char *)&((*m).propellers[3].id))[0] |= (s[53] << 1) & 254;
    ((unsigned char *)&((*m).propellers[3].status))[0] = (s[53] >> 7) & 1;
    ((unsigned char *)&((*m).propellers[3].status))[0] |= (s[54] << 1) & 2;
    ((unsigned char *)&((*m).propellers[3].direction))[0] = (s[54] >> 1) & 3;
    ((unsigned char *)&((*m).power.battery))[0] = (s[54] >> 3) & 31;
    ((unsigned char *)&((*m).power.battery))[0] |= (s[55] << 5) & 224;
    ((unsigned char *)&((*m).power.status))[0] = (s[55] >> 3) & 3;
    ((unsigned char *)&((*m).power.is_charging))[0] = (s[55] >> 5) & 1;
    ((unsigned char *)&((*m).network.signal))[0] = (s[55] >> 6) & 3;
    ((unsigned char *)&((*m).network.signal))[0] |= (s[56] << 2) & 12;
    ((unsigned char *)&((*m).network.heartbeat_at))[0] = (s[56] >> 2) & 63;
    ((unsigned char *)&((*m).network.heartbeat_at))[0] |= (s[57] << 6) & 192;
    ((unsigned char *)&((*m).network.heartbeat_at))[1] = (s[57] >> 2) & 63;
    ((unsigned char *)&((*m).network.heartbeat_at))[1] |= (s[58] << 6) & 192;
    ((unsigned char *)&((*m).network.heartbeat_at))[2] = (s[58] >> 2) & 63;
    ((unsigned char *)&((*m).network.heartbeat_at))[2] |= (s[59] << 6) & 192;
    ((unsigned char *)&((*m).network.heartbeat_at))[3] = (s[59] >> 2) & 63;
    ((unsigned char *)&((*m).network.heartbeat_at))[3] |= (s[60] << 6) & 192;
    ((unsigned char *)&((*m).network.heartbeat_at))[4] = (s[60] >> 2) & 63;
    ((unsigned char *)&((*m).network.heartbeat_at))[4] |= (s[61] << 6) & 192;
    ((unsigned char *)&((*m).network.heartbeat_at))[5] = (s[61] >> 2) & 63;
    ((unsigned char *)&((*m).network.heartbeat_at))[5] |= (s[62] << 6) & 192;
    ((unsigned char *)&((*m).network.heartbeat_at))[6] = (s[62] >> 2) & 63;
    ((unsigned char *)&((*m).network.heartbeat_at))[6] |= (s[63] << 6) & 192;
    ((unsigned char *)&((*m).network.heartbeat_at))[7] = (s[63] >> 2) & 63;
    ((unsigned char *)&((*m).network.heartbeat_at))[7] |= (s[64] << 6) & 192;
    ((unsigned char *)&((*m).landing_gear.status))[0] = (s[64] >> 2) & 3;
#else
    memset(m, 0, sizeof(*m));
    (*m).status |= (DroneStatus)(((unsigned)(s[0])) & 7);
    (*m).position.latitude |= (uint32_t)(((unsigned)(s[0])>> 3) & 31);
    (*m).position.latitude |= (uint32_t)(((unsigned)(s[1])<< 5) & 224);
    (*m).position.latitude |= (uint32_t)((uint32_t)(((unsigned)(s[1])>> 3) & 31) << 8);
    (*m).position.latitude |= (uint32_t)((uint32_t)(((unsigned)(s[2])<< 5) & 224) << 8);
    (*m).position.latitude |= (uint32_t)((uint32_t)(((unsigned)(s[2])>> 3) & 31) << 16);
    (*m).position.latitude |= (uint32_t)((uint32_t)(((unsigned)(s[3])<< 5) & 224) << 16);
    (*m).position.latitude |= (uint32_t)((uint32_t)(((unsigned)(s[3])>> 3) & 31) << 24);
    (*m).position.latitude |= (uint32_t)((uint32_t)(((unsigned)(s[4])<< 5) & 224) << 24);
    (*m).position.longitude |= (uint32_t)(((unsigned)(s[4])>> 3) & 31);
    (*m).position.longitude |= (uint32_t)(((unsigned)(s[5])<< 5) & 224);
    (*m).position.longitude |= (uint32_t)((uint32_t)(((unsigned)(s[5])>> 3) & 31) << 8);
    (*m).position.longitude |= (uint32_t)((uint32_t)(((unsigned)(s[6])<< 5) & 224) << 8);
    (*m).position.longitude |= (uint32_t)((uint32_t)(((unsigned)(s[6])>> 3) & 31) << 16);
    (*m).position.longitude |= (uint32_t)((uint32_t)(((unsigned)(s[7])<< 5) & 224) << 16);
    (*m).position.longitude |= (uint32_t)((uint32_t)(((unsigned)(s[7])>> 3) & 31) << 24);
    (*m).position.longitude |= (uint32_t)((uint32_t)(((unsigned)(s[8])<< 5) & 224) << 24);
    (*m).position.altitude |= (uint32_t)(((unsigned)(s[8])>> 3) & 31);
    (*m).position.altitude |= (uint32_t)(((unsigned)(s[9])<< 5) & 224);
    (*m).position.altitude |= (uint32_t)((uint32_t)(((unsigned)(s[9])>> 3) & 31) << 8);
    (*m).position.altitude |= (uint32_t)((uint32_t)(((unsigned)(s[10])<< 5) & 224) << 8);
    (*m).position.altitude |= (uint32_t)((uint32_t)(((unsigned)(s[10])>> 3) & 31) << 16);
    (*m).position.altitude |= (uint32_t)((uint32_t)(((unsigned)(s[11])<< 5) & 224) << 16);
    (*m).position.altitude |= (uint32_t)((uint32_t)(((unsigned)(s[11])>> 3) & 31) << 24);
    (*m).position.altitude |= (uint32_t)((uint32_t)(((unsigned)(s[12])<< 5) & 224) << 24);
    (*m).flight.pose.yaw |= (int32_t)(((unsigned)(s[12])>> 3) & 31);
    (*m).flight.pose.yaw |= (int32_t)(((unsigned)(s[13])<< 5) & 224);
    (*m).flight.pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[13])>> 3) & 31) << 8);
    (*m).flight.pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[14])<< 5) & 224) << 8);
    (*m).flight.pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[14])>> 3) & 31) << 16);
    (*m).flight.pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[15])<< 5) & 224) << 16);
    (*m).flight.pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[15])>> 3) & 31) << 24);
    (*m).flight.pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[16])<< 5) & 224) << 24);
    (*m).flight.pose.pitch |= (int32_t)(((unsigned)(s[16])>> 3) & 31);
    (*m).flight.pose.pitch |= (int32_t)(((unsigned)(s[17])<< 5) & 224);
    (*m).flight.pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[17])>> 3) & 31) << 8);
    (*m).flight.pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[18])<< 5) & 224) << 8);
    (*m).flight.pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[18])>> 3) & 31) << 16);
    (*m).flight.pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[19])<< 5) & 224) << 16);
    (*m).flight.pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[19])>> 3) & 31) << 24);
    (*m).flight.pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[20])<< 5) & 224) << 24);
    (*m).flight.pose.roll |= (int32_t)(((unsigned)(s[20])>> 3) & 31);
    (*m).flight.pose.roll |= (int32_t)(((unsigned)(s[21])<< 5) & 224);
    (*m).flight.pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[21])>> 3) & 31) << 8);
    (*m).flight.pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[22])<< 5) & 224) << 8);
    (*m).flight.pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[22])>> 3) & 31) << 16);
    (*m).flight.pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[23])<< 5) & 224) << 16);
    (*m).flight.pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[23])>> 3) & 31) << 24);
    (*m).flight.pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[24])<< 5) & 224) << 24);
    (*m).flight.velocity[0] |= (int32_t)(((unsigned)(s[24])>> 3) & 31);
    (*m).flight.velocity[0] |= (int32_t)(((unsigned)(s[25])<< 5) & 224);
    (*m).flight.velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[25])>> 3) & 31) << 8);
    (*m).flight.velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[26])<< 5) & 224) << 8);
    (*m).flight.velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[26])>> 3) & 31) << 16);
    (*m).flight.velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[27])<< 5) & 224) << 16);
    (*m).flight.velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[27])>> 3) & 31) << 24);
    (*m).flight.velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[28])<< 5) & 224) << 24);
    (*m).flight.velocity[1] |= (int32_t)(((unsigned)(s[28])>> 3) & 31);
    (*m).flight.velocity[1] |= (int32_t)(((unsigned)(s[29])<< 5) & 224);
    (*m).flight.velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[29])>> 3) & 31) << 8);
    (*m).flight.velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[30])<< 5) & 224) << 8);
    (*m).flight.velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[30])>> 3) & 31) << 16);
    (*m).flight.velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[31])<< 5) & 224) << 16);
    (*m).flight.velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[31])>> 3) & 31) << 24);
    (*m).flight.velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[32])<< 5) & 224) << 24);
    (*m).flight.velocity[2] |= (int32_t)(((unsigned)(s[32])>> 3) & 31);
    (*m).flight.velocity[2] |= (int32_t)(((unsigned)(s[33])<< 5) & 224);
    (*m).flight.velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[33])>> 3) & 31) << 8);
    (*m).flight.velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[34])<< 5) & 224) << 8);
    (*m).flight.velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[34])>> 3) & 31) << 16);
    (*m).flight.velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[35])<< 5) & 224) << 16);
    (*m).flight.velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[35])>> 3) & 31) << 24);
    (*m).flight.velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[36])<< 5) & 224) << 24);
    (*m).flight.acceleration[0] |= (int32_t)(((unsigned)(s[36])>> 3) & 31);
    (*m).flight.acceleration[0] |= (int32_t)(((unsigned)(s[37])<< 5) & 224);
    (*m).flight.acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[37])>> 3) & 31) << 8);
    (*m).flight.acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[38])<< 5) & 224) << 8);
    (*m).flight.acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[38])>> 3) & 31) << 16);
    (*m).flight.acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[39])<< 5) & 224) << 16);
    (*m).flight.acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[39])>> 3) & 31) << 24);
    (*m).flight.acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[40])<< 5) & 224) << 24);
    (*m).flight.acceleration[1] |= (int32_t)(((unsigned)(s[40])>> 3) & 31);
    (*m).flight.acceleration[1] |= (int32_t)(((unsigned)(s[41])<< 5) & 224);
    (*m).flight.acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[41])>> 3) & 31) << 8);
    (*m).flight.acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[42])<< 5) & 224) << 8);
    (*m).flight.acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[42])>> 3) & 31) << 16);
    (*m).flight.acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[43])<< 5) & 224) << 16);
    (*m).flight.acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[43])>> 3) & 31) << 24);
    (*m).flight.acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[44])<< 5) & 224) << 24);
    (*m).flight.acceleration[2] |= (int32_t)(((unsigned)(s[44])>> 3) & 31);
    (*m).flight.acceleration[2] |= (int32_t)(((unsigned)(s[45])<< 5) & 224);
    (*m).flight.acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[45])>> 3) & 31) << 8);
    (*m).flight.acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[46])<< 5) & 224) << 8);
    (*m).flight.acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[46])>> 3) & 31) << 16);
    (*m).flight.acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[47])<< 5) & 224) << 16);
    (*m).flight.acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[47])>> 3) & 31) << 24);
    (*m).flight.acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[48])<< 5) & 224) << 24);
    (*m).propellers[0].id |= (uint8_t)(((unsigned)(s[48])>> 3) & 31);
    (*m).propellers[0].id |= (uint8_t)(((unsigned)(s[49])<< 5) & 224);
    (*m).propellers[0].status |= (PropellerStatus)(((unsigned)(s[49])>> 3) & 3);
    (*m).propellers[0].direction |= (RotatingDirection)(((unsigned)(s[49])>> 5) & 3);
    (*m).propellers[1].id |= (uint8_t)(((unsigned)(s[49])>> 7) & 1);
    (*m).propellers[1].id |= (uint8_t)(((unsigned)(s[50])<< 1) & 254);
    (*m).propellers[1].status |= (PropellerStatus)(((unsigned)(s[50])>> 7) & 1);
    (*m).propellers[1].status |= (PropellerStatus)(((unsigned)(s[51])<< 1) & 2);
    (*m).propellers[1].direction |= (RotatingDirection)(((unsigned)(s[51])>> 1) & 3);
    (*m).propellers[2].id |= (uint8_t)(((unsigned)(s[51])>> 3) & 31);
    (*m).propellers[2].id |= (uint8_t)(((unsigned)(s[52])<< 5) & 224);
    (*m).propellers[2].status |= (PropellerStatus)(((unsigned)(s[52])>> 3) & 3);
    (*m).propellers[2].direction |= (RotatingDirection)(((unsigned)(s[52])>> 5) & 3);
    (*m).propellers[3].id |= (uint8_t)(((unsigned)(s[52])>> 7) & 1);
    (*m).propellers[3].id |= (uint8_t)(((unsigned)(s[53])<< 1) & 254);
    (*m).propellers[3].status |= (PropellerStatus)(((unsigned)(s[53])>> 7) & 1);
    (*m).propellers[3].status |= (PropellerStatus)(((unsigned)(s[54])<< 1) & 2);
    (*m).propellers[3].direction |= (RotatingDirection)(((unsigned)(s[54])>> 1) & 3);
    (*m).power.battery |= (uint8_t)(((unsigned)(s[54])>> 3) & 31);
    (*m).power.battery |= (uint8_t)(((unsigned)(s[55])<< 5) & 224);
    (*m).power.status |= (PowerStatus)(((unsigned)(s[55])>> 3) & 3);
    (*m).power.is_charging |= (bool)(((unsigned)(s[55])>> 5) & 1);
    (*m).network.signal |= (uint8_t)(((unsigned)(s[55])>> 6) & 3);
    (*m).network.signal |= (uint8_t)(((unsigned)(s[56])<< 2) & 12);
    (*m).network.heartbeat_at |= (Timestamp)(((unsigned)(s[56])>> 2) & 63);
    (*m).network.heartbeat_at |= (Timestamp)(((unsigned)(s[57])<< 6) & 192);
    (*m).network.heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[57])>> 2) & 63) << 8);
    (*m).network.heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[58])<< 6) & 192) << 8);
    (*m).network.heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[58])>> 2) & 63) << 16);
    (*m).network.heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[59])<< 6) & 192) << 16);
    (*m).network.heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[59])>> 2) & 63) << 24);
    (*m).network.heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[60])<< 6) & 192) << 24);
    (*m).network.heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[60])>> 2) & 63) << 32);
    (*m).network.heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[61])<< 6) & 192) << 32);
    (*m).network.heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[61])>> 2) & 63) << 40);
    (*m).network.heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[62])<< 6) & 192) << 40);
    (*m).network.heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[62])>> 2) & 63) << 48);
    (*m).network.heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[63])<< 6) & 192) << 48);
    (*m).network.heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[63])>> 2) & 63) << 56);
    (*m).network.heartbeat_at |= (Timestamp)((uint64_t)(((unsigned)(s[64])<< 6) & 192) << 56);
    (*m).landing_gear.status |= (LandingGearStatus)(((unsigned)(s[64])>> 2) & 3);
#endif
    return BYTES_LENGTH_DRONE;
}