// Code generated by bitproto-go native renderer (experimental). DO NOT EDIT.
#ifndef __BITPROTO_NATIVE_FRAMEHEADER_H__
#define __BITPROTO_NATIVE_FRAMEHEADER_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#include <limits.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#define BP_FLOAT_SCALE 100000000.0
// static inline int32_t BpFloatToInt32(double v) {
//     double s = v * BP_FLOAT_SCALE;
//     if (s > (double)INT32_MAX) { return INT32_MAX; }
//     if (s < (double)INT32_MIN) { return INT32_MIN; }
//     return (int32_t)(s >= 0 ? (s + 0.5) : (s - 0.5));
// }
// static inline double BpInt32ToFloat(int32_t v) {
//     return ((double)v) / BP_FLOAT_SCALE;
// }

typedef uint8_t PayloadType;
#define PAYLOAD_TYPE_UNKNOWN 0
#define PAYLOAD_TYPE_DRONE 1

typedef uint8_t ProtocolVersion;
#define PROTOCOL_VERSION_UNKNOWN 0
#define PROTOCOL_VERSION_V1 1

struct FrameHeader {
    uint8_t magic;
    ProtocolVersion version;
    PayloadType payload_type;
    uint16_t payload_length;
};

#define BYTES_LENGTH_FRAMEHEADER 4

size_t EncodeFrameHeader(struct FrameHeader *m, unsigned char *s);
size_t DecodeFrameHeader(struct FrameHeader *m, unsigned char *s);
int JsonFrameHeader(struct FrameHeader *m, char *s);


#endif
