// Code generated by bitproto. DO NOT EDIT.

#include "frame_header_bp.h"
#if !defined(BP_BIG_ENDIAN) && (\
    (defined(__BYTE_ORDER__) && (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)) || \
    defined(__ARM_BIG_ENDIAN) || \
    defined(__big_endian__) || \
    defined(__BIG_ENDIAN__) || \
    (defined(__LITTLE_ENDIAN__) && (__LITTLE_ENDIAN__ == 0)))
#define BP_BIG_ENDIAN 1
#endif
#ifdef BP_BIG_ENDIAN
#include <string.h>
#endif

size_t EncodeFrameHeader(struct FrameHeader *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    s[0] = (((unsigned char *)&((*m).magic))[0] ) & 255;
    s[1] = (((unsigned char *)&((*m).payload_type))[0] ) & 255;
    s[2] = (((unsigned char *)&((*m).payload_length))[0] ) & 255;
    s[3] = (((unsigned char *)&((*m).payload_length))[1] ) & 255;
#else
    s[0] = ((uint8_t)((*m).magic)) & 255;
    s[1] = ((uint8_t)((*m).payload_type)) & 255;
    s[2] = ((uint16_t)((*m).payload_length)) & 255;
    s[3] = ((uint16_t)((*m).payload_length)>> 8) & 255;
#endif
    return BYTES_LENGTH_FRAME_HEADER;
}

size_t DecodeFrameHeader(struct FrameHeader *m, unsigned char *s) {
#ifndef BP_BIG_ENDIAN
    ((unsigned char *)&((*m).magic))[0] = (s[0] ) & 255;
    ((unsigned char *)&((*m).payload_type))[0] = (s[1] ) & 255;
    ((unsigned char *)&((*m).payload_length))[0] = (s[2] ) & 255;
    ((unsigned char *)&((*m).payload_length))[1] = (s[3] ) & 255;
#else
    memset(m, 0, sizeof(*m));
    (*m).magic |= (uint8_t)(((unsigned)(s[0])) & 255);
    (*m).payload_type |= (PayloadType)(((unsigned)(s[1])) & 255);
    (*m).payload_length |= (uint16_t)(((unsigned)(s[2])) & 255);
    (*m).payload_length |= (uint16_t)((uint16_t)(((unsigned)(s[3])) & 255) << 8);
#endif
    return BYTES_LENGTH_FRAME_HEADER;
}