// Code generated by bitproto-go native renderer (experimental). DO NOT EDIT.
#include "bitproto.h"
#include "frameheader_bp.h"

void BpNativeProcessFrameHeader(void *data, struct BpProcessorContext *ctx);
void BpNativeJsonFormatFrameHeader(void *data, struct BpJsonFormatContext *ctx);

void BpFieldDescriptorsInitFrameHeader(struct FrameHeader *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->magic), BpUint(8, sizeof(uint8_t)), "magic");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->version), BpEnum(3, sizeof(ProtocolVersion)), "version");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->payload_type), BpEnum(5, sizeof(PayloadType)), "payload_type");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->payload_length), BpUint(16, sizeof(uint16_t)), "payload_length");
}

void BpNativeProcessFrameHeader(void *data, struct BpProcessorContext *ctx) {
    struct FrameHeader *m = (struct FrameHeader *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitFrameHeader(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 32, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpNativeJsonFormatFrameHeader(void *data, struct BpJsonFormatContext *ctx) {
    struct FrameHeader *m = (struct FrameHeader *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitFrameHeader(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 32, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

size_t EncodeFrameHeader(struct FrameHeader *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpNativeProcessFrameHeader((void *)m, &ctx);
    return BYTES_LENGTH_FRAMEHEADER;
}

size_t DecodeFrameHeader(struct FrameHeader *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpNativeProcessFrameHeader((void *)m, &ctx);
    return BYTES_LENGTH_FRAMEHEADER;
}

int JsonFrameHeader(struct FrameHeader *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpNativeJsonFormatFrameHeader((void *)m, &ctx);
    return ctx.n;
}

