// Code generated by bitproto-go native renderer (experimental). DO NOT EDIT.
#ifndef __BITPROTO__FRAMEHEADER_H__
#define __BITPROTO__FRAMEHEADER_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

#define FRAME_MAGIC 0xB1

typedef uint8_t PayloadType;
#define PAYLOAD_TYPE_UNKNOWN 0
#define PAYLOAD_TYPE_DRONE 1
#define PAYLOAD_TYPE_HEARTBEAT 2
#define PAYLOAD_TYPE_COMMAND 3
#define PAYLOAD_TYPE_FLIGHT 4
#define PAYLOAD_TYPE_POSITION 5
#define PAYLOAD_TYPE_MOVEMENT 6
#define PAYLOAD_TYPE_RESULT 7

typedef uint8_t ProtocolVersion;
#define PROTOCOL_VERSION_UNKNOWN 0
#define PROTOCOL_VERSION_V1 1

struct FrameHeader {
    uint8_t magic;
    ProtocolVersion version;
    PayloadType payload_type;
    uint16_t payload_length;
};

#define BYTES_LENGTH_FRAMEHEADER 4

size_t EncodeFrameHeader(struct FrameHeader *m, unsigned char *s);
size_t DecodeFrameHeader(struct FrameHeader *m, unsigned char *s);
int JsonFrameHeader(struct FrameHeader *m, char *s);


#if defined(__cplusplus)
}
#endif

#endif
