// Code generated by bitproto. DO NOT EDIT.

// Frame header schema shared by C and Go for TCP stream framing.

#ifndef __BITPROTO__FRAMEHEADER_H__
#define __BITPROTO__FRAMEHEADER_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#define BITPROTO_OPTIMIZATION_MODE 1

typedef uint8_t PayloadType; // 8bit

#define PAYLOAD_TYPE_UNKNOWN 0
#define PAYLOAD_TYPE_DRONE 1

// Number of bytes to encode struct FrameHeader
#define BYTES_LENGTH_FRAME_HEADER 4

struct FrameHeader {
    uint8_t magic; // 8bit
    PayloadType payload_type; // 8bit
    uint16_t payload_length; // 16bit
};

// Encode struct FrameHeader to given buffer s.
size_t EncodeFrameHeader(struct FrameHeader *m, unsigned char *s);
// Decode struct FrameHeader from given buffer s.
size_t DecodeFrameHeader(struct FrameHeader *m, unsigned char *s);

#if defined(__cplusplus)
}
#endif

#endif