# 调整 Flash 物理大小配置为 4MB
CONFIG_FLASH_SIZE=4096

# 如果使用的是 ESP32 系列芯片，确保引导程序（Bootloader）的 Flash 大小也同步修改
# CONFIG_ESP_BOOTLOADER_FLASH_SIZE_4MB=y


CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y
# CONFIG_MAIN_STACK_SIZE=6144
# CONFIG_HEAP_MEM_POOL_SIZE=4096

CONFIG_NETWORKING=y
CONFIG_NET_NATIVE=n
CONFIG_NET_OFFLOAD=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_NET_SOCKETS_OFFLOAD_PRIORITY=40
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_UDP=n
CONFIG_NET_DHCPV4=n
CONFIG_EC801E=y
CONFIG_EC801E_APN="CMNET"

# 基础控制台打印使能
CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_UART_CONSOLE=y

# FS
# =========================================================================
# 1. 文件系统与磁盘管理器 (物理 Flash 持久化驱动)
# =========================================================================
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_MKFS=y
CONFIG_FILE_SYSTEM_MKFS=y

# 启用底层物理 Flash 存储映射驱动
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVER_FLASH=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y

# =========================================================================
# 2. 现代新版 USB 堆栈 (USB Device Next) 核心配置
# =========================================================================
# 【核心修正】：Zephyr 4.4.1 标准命名符号为 STACK_NEXT
CONFIG_USB_DEVICE_STACK_NEXT=y

# 启用大容量存储设备（MSC）
CONFIG_USBD_MSC_CLASS=y

# 启用 CDC ACM 虚拟串口（与 MSC 组成复合 USB 设备）
CONFIG_USBD_CDC_ACM_CLASS=y

# 控制单设备实例内的最大逻辑单元数量 (默认设为 1 即可满足单 U 盘挂载)
CONFIG_USBD_MSC_LUNS_PER_INSTANCE=1

 



