// Code generated by bitproto-go native renderer (experimental). DO NOT EDIT.

package drone

import (
	"encoding/json"
	bp "github.com/tsingson/bitproto/lib/go"
	"strconv"
)

var formatInt = strconv.FormatInt
var jsonMarshal = json.Marshal
var _ = bp.Useless

type Timestamp int64

func (m Timestamp) BpProcessor() bp.Processor {
	return bp.NewAliasProcessor(bp.NewInt(64))
}

type TernaryInt32 [3]int32

func (m TernaryInt32) BpProcessor() bp.Processor {
	return bp.NewAliasProcessor(bp.NewArray(false, 3, bp.NewInt(32)))
}

type DroneStatus uint8

const (
	DRONE_STATUS_UNKNOWN DroneStatus = 0
	DRONE_STATUS_STANDBY             = 1
	DRONE_STATUS_RISING              = 2
	DRONE_STATUS_LANDING             = 3
	DRONE_STATUS_FLYING              = 4
)

func (m DroneStatus) BpProcessor() bp.Processor {
	return bp.NewEnumProcessor(bp.NewUint(3))
}

func (v DroneStatus) String() string {
	switch v {
	case 0:
		return "DRONE_STATUS_UNKNOWN"
	case 1:
		return "DRONE_STATUS_STANDBY"
	case 2:
		return "DRONE_STATUS_RISING"
	case 3:
		return "DRONE_STATUS_LANDING"
	case 4:
		return "DRONE_STATUS_FLYING"
	default:
		return "DroneStatus(" + formatInt(int64(v), 10) + ")"
	}
}

type PropellerStatus uint8

const (
	PROPELLER_STATUS_UNKNOWN  PropellerStatus = 0
	PROPELLER_STATUS_IDLE                     = 1
	PROPELLER_STATUS_ROTATING                 = 2
)

func (m PropellerStatus) BpProcessor() bp.Processor {
	return bp.NewEnumProcessor(bp.NewUint(2))
}

func (v PropellerStatus) String() string {
	switch v {
	case 0:
		return "PROPELLER_STATUS_UNKNOWN"
	case 1:
		return "PROPELLER_STATUS_IDLE"
	case 2:
		return "PROPELLER_STATUS_ROTATING"
	default:
		return "PropellerStatus(" + formatInt(int64(v), 10) + ")"
	}
}

type RotatingDirection uint8

const (
	ROTATING_DIRECTION_UNKNOWN         RotatingDirection = 0
	ROTATING_DIRECTION_CLOCK_WISE                        = 1
	ROTATING_DIRECTION_ANTI_CLOCK_WISE                   = 2
)

func (m RotatingDirection) BpProcessor() bp.Processor {
	return bp.NewEnumProcessor(bp.NewUint(2))
}

func (v RotatingDirection) String() string {
	switch v {
	case 0:
		return "ROTATING_DIRECTION_UNKNOWN"
	case 1:
		return "ROTATING_DIRECTION_CLOCK_WISE"
	case 2:
		return "ROTATING_DIRECTION_ANTI_CLOCK_WISE"
	default:
		return "RotatingDirection(" + formatInt(int64(v), 10) + ")"
	}
}

type PowerStatus uint8

const (
	POWER_STATUS_UNKNOWN PowerStatus = 0
	POWER_STATUS_OFF                 = 1
	POWER_STATUS_ON                  = 2
)

func (m PowerStatus) BpProcessor() bp.Processor {
	return bp.NewEnumProcessor(bp.NewUint(2))
}

func (v PowerStatus) String() string {
	switch v {
	case 0:
		return "POWER_STATUS_UNKNOWN"
	case 1:
		return "POWER_STATUS_OFF"
	case 2:
		return "POWER_STATUS_ON"
	default:
		return "PowerStatus(" + formatInt(int64(v), 10) + ")"
	}
}

type LandingGearStatus uint8

const (
	LANDING_GEAR_STATUS_UNKNOWN  LandingGearStatus = 0
	LANDING_GEAR_STATUS_UNFOLDED                   = 1
	LANDING_GEAR_STATUS_FOLDED                     = 2
)

func (m LandingGearStatus) BpProcessor() bp.Processor {
	return bp.NewEnumProcessor(bp.NewUint(2))
}

func (v LandingGearStatus) String() string {
	switch v {
	case 0:
		return "LANDING_GEAR_STATUS_UNKNOWN"
	case 1:
		return "LANDING_GEAR_STATUS_UNFOLDED"
	case 2:
		return "LANDING_GEAR_STATUS_FOLDED"
	default:
		return "LandingGearStatus(" + formatInt(int64(v), 10) + ")"
	}
}

type Propeller struct {
	Id        uint8             `json:"id"`
	Status    PropellerStatus   `json:"status"`
	Direction RotatingDirection `json:"direction"`
}

type Power struct {
	Battery    uint8       `json:"battery"`
	Status     PowerStatus `json:"status"`
	IsCharging bool        `json:"is_charging"`
}

type Network struct {
	Signal      uint8     `json:"signal"`
	HeartbeatAt Timestamp `json:"heartbeat_at"`
}

type LandingGear struct {
	Status LandingGearStatus `json:"status"`
}

type Position struct {
	Latitude  int32 `json:"latitude"`
	Longitude int32 `json:"longitude"`
	Altitude  int32 `json:"altitude"`
}

type Pose struct {
	Yaw   int32 `json:"yaw"`
	Pitch int32 `json:"pitch"`
	Roll  int32 `json:"roll"`
}

type Flight struct {
	Pose         Pose         `json:"pose"`
	Velocity     TernaryInt32 `json:"velocity"`
	Acceleration TernaryInt32 `json:"acceleration"`
}

type Drone struct {
	Status      DroneStatus  `json:"status"`
	Position    Position     `json:"position"`
	Flight      Flight       `json:"flight"`
	Propellers  [4]Propeller `json:"propellers"`
	Power       Power        `json:"power"`
	Network     Network      `json:"network"`
	LandingGear LandingGear  `json:"landing_gear"`
}

const BYTES_LENGTH_PROPELLER uint32 = 2
const BYTES_LENGTH_POWER uint32 = 2
const BYTES_LENGTH_NETWORK uint32 = 9
const BYTES_LENGTH_LANDINGGEAR uint32 = 1
const BYTES_LENGTH_POSITION uint32 = 12
const BYTES_LENGTH_POSE uint32 = 12
const BYTES_LENGTH_FLIGHT uint32 = 36
const BYTES_LENGTH_DRONE uint32 = 65

func (m *Propeller) Size() uint32 { return BYTES_LENGTH_PROPELLER }

func (m *Propeller) String() string {
	v, _ := jsonMarshal(m)
	return string(v)
}

func (m *Propeller) Encode() []byte {
	ctx := bp.NewEncodeContext(int(m.Size()))
	m.BpProcessor().Process(ctx, nil, m)
	return ctx.Buffer()
}

func (m *Propeller) Decode(s []byte) {
	ctx := bp.NewDecodeContext(s)
	m.BpProcessor().Process(ctx, nil, m)
}

func (m *Propeller) BpProcessor() bp.Processor {
	fieldDescriptors := []*bp.MessageFieldProcessor{
		bp.NewMessageFieldProcessor(1, bp.NewUint(8)),
		bp.NewMessageFieldProcessor(2, (PropellerStatus(0)).BpProcessor()),
		bp.NewMessageFieldProcessor(3, (RotatingDirection(0)).BpProcessor()),
	}
	return bp.NewMessageProcessor(false, 12, fieldDescriptors)
}

func (m *Propeller) BpGetAccessor(di *bp.DataIndexer) bp.Accessor {
	switch di.F() {
	default:
		return nil
	}
}

func (m *Propeller) BpSetByte(di *bp.DataIndexer, lshift int, bt byte) {
	switch di.F() {
	case 1:
		m.Id |= (uint8(bt) << lshift)
	case 2:
		m.Status |= (PropellerStatus(bt) << lshift)
	case 3:
		m.Direction |= (RotatingDirection(bt) << lshift)
	default:
		return
	}
}

func (m *Propeller) BpGetByte(di *bp.DataIndexer, rshift int) byte {
	switch di.F() {
	case 1:
		return byte(m.Id >> rshift)
	case 2:
		return byte(m.Status >> rshift)
	case 3:
		return byte(m.Direction >> rshift)
	default:
		return byte(0)
	}
}

func (m *Propeller) BpProcessInt(di *bp.DataIndexer) {
	switch di.F() {
	default:
		return
	}
}

func (m *Power) Size() uint32 { return BYTES_LENGTH_POWER }

func (m *Power) String() string {
	v, _ := jsonMarshal(m)
	return string(v)
}

func (m *Power) Encode() []byte {
	ctx := bp.NewEncodeContext(int(m.Size()))
	m.BpProcessor().Process(ctx, nil, m)
	return ctx.Buffer()
}

func (m *Power) Decode(s []byte) {
	ctx := bp.NewDecodeContext(s)
	m.BpProcessor().Process(ctx, nil, m)
}

func (m *Power) BpProcessor() bp.Processor {
	fieldDescriptors := []*bp.MessageFieldProcessor{
		bp.NewMessageFieldProcessor(1, bp.NewUint(8)),
		bp.NewMessageFieldProcessor(2, (PowerStatus(0)).BpProcessor()),
		bp.NewMessageFieldProcessor(3, bp.NewBool()),
	}
	return bp.NewMessageProcessor(false, 11, fieldDescriptors)
}

func (m *Power) BpGetAccessor(di *bp.DataIndexer) bp.Accessor {
	switch di.F() {
	default:
		return nil
	}
}

func (m *Power) BpSetByte(di *bp.DataIndexer, lshift int, bt byte) {
	switch di.F() {
	case 1:
		m.Battery |= (uint8(bt) << lshift)
	case 2:
		m.Status |= (PowerStatus(bt) << lshift)
	case 3:
		m.IsCharging = bp.Byte2bool(bt)
	default:
		return
	}
}

func (m *Power) BpGetByte(di *bp.DataIndexer, rshift int) byte {
	switch di.F() {
	case 1:
		return byte(m.Battery >> rshift)
	case 2:
		return byte(m.Status >> rshift)
	case 3:
		return bp.Bool2byte(m.IsCharging) >> rshift
	default:
		return byte(0)
	}
}

func (m *Power) BpProcessInt(di *bp.DataIndexer) {
	switch di.F() {
	default:
		return
	}
}

func (m *Network) Size() uint32 { return BYTES_LENGTH_NETWORK }

func (m *Network) String() string {
	v, _ := jsonMarshal(m)
	return string(v)
}

func (m *Network) Encode() []byte {
	ctx := bp.NewEncodeContext(int(m.Size()))
	m.BpProcessor().Process(ctx, nil, m)
	return ctx.Buffer()
}

func (m *Network) Decode(s []byte) {
	ctx := bp.NewDecodeContext(s)
	m.BpProcessor().Process(ctx, nil, m)
}

func (m *Network) BpProcessor() bp.Processor {
	fieldDescriptors := []*bp.MessageFieldProcessor{
		bp.NewMessageFieldProcessor(1, bp.NewUint(4)),
		bp.NewMessageFieldProcessor(2, (Timestamp(0)).BpProcessor()),
	}
	return bp.NewMessageProcessor(false, 68, fieldDescriptors)
}

func (m *Network) BpGetAccessor(di *bp.DataIndexer) bp.Accessor {
	switch di.F() {
	default:
		return nil
	}
}

func (m *Network) BpSetByte(di *bp.DataIndexer, lshift int, bt byte) {
	switch di.F() {
	case 1:
		m.Signal |= (uint8(bt) << lshift)
	case 2:
		m.HeartbeatAt |= (Timestamp(bt) << lshift)
	default:
		return
	}
}

func (m *Network) BpGetByte(di *bp.DataIndexer, rshift int) byte {
	switch di.F() {
	case 1:
		return byte(m.Signal >> rshift)
	case 2:
		return byte(m.HeartbeatAt >> rshift)
	default:
		return byte(0)
	}
}

func (m *Network) BpProcessInt(di *bp.DataIndexer) {
	switch di.F() {
	default:
		return
	}
}

func (m *LandingGear) Size() uint32 { return BYTES_LENGTH_LANDINGGEAR }

func (m *LandingGear) String() string {
	v, _ := jsonMarshal(m)
	return string(v)
}

func (m *LandingGear) Encode() []byte {
	ctx := bp.NewEncodeContext(int(m.Size()))
	m.BpProcessor().Process(ctx, nil, m)
	return ctx.Buffer()
}

func (m *LandingGear) Decode(s []byte) {
	ctx := bp.NewDecodeContext(s)
	m.BpProcessor().Process(ctx, nil, m)
}

func (m *LandingGear) BpProcessor() bp.Processor {
	fieldDescriptors := []*bp.MessageFieldProcessor{
		bp.NewMessageFieldProcessor(1, (LandingGearStatus(0)).BpProcessor()),
	}
	return bp.NewMessageProcessor(false, 2, fieldDescriptors)
}

func (m *LandingGear) BpGetAccessor(di *bp.DataIndexer) bp.Accessor {
	switch di.F() {
	default:
		return nil
	}
}

func (m *LandingGear) BpSetByte(di *bp.DataIndexer, lshift int, bt byte) {
	switch di.F() {
	case 1:
		m.Status |= (LandingGearStatus(bt) << lshift)
	default:
		return
	}
}

func (m *LandingGear) BpGetByte(di *bp.DataIndexer, rshift int) byte {
	switch di.F() {
	case 1:
		return byte(m.Status >> rshift)
	default:
		return byte(0)
	}
}

func (m *LandingGear) BpProcessInt(di *bp.DataIndexer) {
	switch di.F() {
	default:
		return
	}
}

func (m *Position) Size() uint32 { return BYTES_LENGTH_POSITION }

func (m *Position) String() string {
	v, _ := jsonMarshal(m)
	return string(v)
}

func (m *Position) SetLatitudeFloat(v float64) {
	m.Latitude = int32(bp.BpFloatToInt32(v))
}

func (m *Position) GetLatitudeFloat() float64 {
	return bp.BpInt32ToFloat(int32(m.Latitude))
}

func (m *Position) SetLongitudeFloat(v float64) {
	m.Longitude = int32(bp.BpFloatToInt32(v))
}

func (m *Position) GetLongitudeFloat() float64 {
	return bp.BpInt32ToFloat(int32(m.Longitude))
}

func (m *Position) SetAltitudeFloat(v float64) {
	m.Altitude = int32(bp.BpFloatToInt32(v))
}

func (m *Position) GetAltitudeFloat() float64 {
	return bp.BpInt32ToFloat(int32(m.Altitude))
}

func (m *Position) Encode() []byte {
	ctx := bp.NewEncodeContext(int(m.Size()))
	m.BpProcessor().Process(ctx, nil, m)
	return ctx.Buffer()
}

func (m *Position) Decode(s []byte) {
	ctx := bp.NewDecodeContext(s)
	m.BpProcessor().Process(ctx, nil, m)
}

func (m *Position) BpProcessor() bp.Processor {
	fieldDescriptors := []*bp.MessageFieldProcessor{
		bp.NewMessageFieldProcessor(1, bp.NewInt(32)),
		bp.NewMessageFieldProcessor(2, bp.NewInt(32)),
		bp.NewMessageFieldProcessor(3, bp.NewInt(32)),
	}
	return bp.NewMessageProcessor(false, 96, fieldDescriptors)
}

func (m *Position) BpGetAccessor(di *bp.DataIndexer) bp.Accessor {
	switch di.F() {
	default:
		return nil
	}
}

func (m *Position) BpSetByte(di *bp.DataIndexer, lshift int, bt byte) {
	switch di.F() {
	case 1:
		m.Latitude |= (int32(bt) << lshift)
	case 2:
		m.Longitude |= (int32(bt) << lshift)
	case 3:
		m.Altitude |= (int32(bt) << lshift)
	default:
		return
	}
}

func (m *Position) BpGetByte(di *bp.DataIndexer, rshift int) byte {
	switch di.F() {
	case 1:
		return byte(m.Latitude >> rshift)
	case 2:
		return byte(m.Longitude >> rshift)
	case 3:
		return byte(m.Altitude >> rshift)
	default:
		return byte(0)
	}
}

func (m *Position) BpProcessInt(di *bp.DataIndexer) {
	switch di.F() {
	default:
		return
	}
}

func (m *Pose) Size() uint32 { return BYTES_LENGTH_POSE }

func (m *Pose) String() string {
	v, _ := jsonMarshal(m)
	return string(v)
}

func (m *Pose) Encode() []byte {
	ctx := bp.NewEncodeContext(int(m.Size()))
	m.BpProcessor().Process(ctx, nil, m)
	return ctx.Buffer()
}

func (m *Pose) Decode(s []byte) {
	ctx := bp.NewDecodeContext(s)
	m.BpProcessor().Process(ctx, nil, m)
}

func (m *Pose) BpProcessor() bp.Processor {
	fieldDescriptors := []*bp.MessageFieldProcessor{
		bp.NewMessageFieldProcessor(1, bp.NewInt(32)),
		bp.NewMessageFieldProcessor(2, bp.NewInt(32)),
		bp.NewMessageFieldProcessor(3, bp.NewInt(32)),
	}
	return bp.NewMessageProcessor(false, 96, fieldDescriptors)
}

func (m *Pose) BpGetAccessor(di *bp.DataIndexer) bp.Accessor {
	switch di.F() {
	default:
		return nil
	}
}

func (m *Pose) BpSetByte(di *bp.DataIndexer, lshift int, bt byte) {
	switch di.F() {
	case 1:
		m.Yaw |= (int32(bt) << lshift)
	case 2:
		m.Pitch |= (int32(bt) << lshift)
	case 3:
		m.Roll |= (int32(bt) << lshift)
	default:
		return
	}
}

func (m *Pose) BpGetByte(di *bp.DataIndexer, rshift int) byte {
	switch di.F() {
	case 1:
		return byte(m.Yaw >> rshift)
	case 2:
		return byte(m.Pitch >> rshift)
	case 3:
		return byte(m.Roll >> rshift)
	default:
		return byte(0)
	}
}

func (m *Pose) BpProcessInt(di *bp.DataIndexer) {
	switch di.F() {
	default:
		return
	}
}

func (m *Flight) Size() uint32 { return BYTES_LENGTH_FLIGHT }

func (m *Flight) String() string {
	v, _ := jsonMarshal(m)
	return string(v)
}

func (m *Flight) Encode() []byte {
	ctx := bp.NewEncodeContext(int(m.Size()))
	m.BpProcessor().Process(ctx, nil, m)
	return ctx.Buffer()
}

func (m *Flight) Decode(s []byte) {
	ctx := bp.NewDecodeContext(s)
	m.BpProcessor().Process(ctx, nil, m)
}

func (m *Flight) BpProcessor() bp.Processor {
	fieldDescriptors := []*bp.MessageFieldProcessor{
		bp.NewMessageFieldProcessor(1, (&Pose{}).BpProcessor()),
		bp.NewMessageFieldProcessor(2, (TernaryInt32{}).BpProcessor()),
		bp.NewMessageFieldProcessor(3, (TernaryInt32{}).BpProcessor()),
	}
	return bp.NewMessageProcessor(false, 288, fieldDescriptors)
}

func (m *Flight) BpGetAccessor(di *bp.DataIndexer) bp.Accessor {
	switch di.F() {
	case 1:
		return &(m.Pose)
	default:
		return nil
	}
}

func (m *Flight) BpSetByte(di *bp.DataIndexer, lshift int, bt byte) {
	switch di.F() {
	case 2:
		m.Velocity[di.I(0)] |= (int32(bt) << lshift)
	case 3:
		m.Acceleration[di.I(0)] |= (int32(bt) << lshift)
	default:
		return
	}
}

func (m *Flight) BpGetByte(di *bp.DataIndexer, rshift int) byte {
	switch di.F() {
	case 2:
		return byte(m.Velocity[di.I(0)] >> rshift)
	case 3:
		return byte(m.Acceleration[di.I(0)] >> rshift)
	default:
		return byte(0)
	}
}

func (m *Flight) BpProcessInt(di *bp.DataIndexer) {
	switch di.F() {
	default:
		return
	}
}

func (m *Drone) Size() uint32 { return BYTES_LENGTH_DRONE }

func (m *Drone) String() string {
	v, _ := jsonMarshal(m)
	return string(v)
}

func (m *Drone) Encode() []byte {
	ctx := bp.NewEncodeContext(int(m.Size()))
	m.BpProcessor().Process(ctx, nil, m)
	return ctx.Buffer()
}

func (m *Drone) Decode(s []byte) {
	ctx := bp.NewDecodeContext(s)
	m.BpProcessor().Process(ctx, nil, m)
}

func (m *Drone) BpProcessor() bp.Processor {
	fieldDescriptors := []*bp.MessageFieldProcessor{
		bp.NewMessageFieldProcessor(1, (DroneStatus(0)).BpProcessor()),
		bp.NewMessageFieldProcessor(2, (&Position{}).BpProcessor()),
		bp.NewMessageFieldProcessor(3, (&Flight{}).BpProcessor()),
		bp.NewMessageFieldProcessor(4, bp.NewArray(false, 4, (&Propeller{}).BpProcessor())),
		bp.NewMessageFieldProcessor(5, (&Power{}).BpProcessor()),
		bp.NewMessageFieldProcessor(6, (&Network{}).BpProcessor()),
		bp.NewMessageFieldProcessor(7, (&LandingGear{}).BpProcessor()),
	}
	return bp.NewMessageProcessor(false, 516, fieldDescriptors)
}

func (m *Drone) BpGetAccessor(di *bp.DataIndexer) bp.Accessor {
	switch di.F() {
	case 2:
		return &(m.Position)
	case 3:
		return &(m.Flight)
	case 4:
		return &(m.Propellers[di.I(0)])
	case 5:
		return &(m.Power)
	case 6:
		return &(m.Network)
	case 7:
		return &(m.LandingGear)
	default:
		return nil
	}
}

func (m *Drone) BpSetByte(di *bp.DataIndexer, lshift int, bt byte) {
	switch di.F() {
	case 1:
		m.Status |= (DroneStatus(bt) << lshift)
	default:
		return
	}
}

func (m *Drone) BpGetByte(di *bp.DataIndexer, rshift int) byte {
	switch di.F() {
	case 1:
		return byte(m.Status >> rshift)
	default:
		return byte(0)
	}
}

func (m *Drone) BpProcessInt(di *bp.DataIndexer) {
	switch di.F() {
	default:
		return
	}
}
