// Code generated by bitproto-go native renderer (experimental). DO NOT EDIT.

package frameheader

import (
	"encoding/json"
	bp "github.com/tsingson/bitproto/lib/go"
	"strconv"
)

var formatInt = strconv.FormatInt
var jsonMarshal = json.Marshal
var _ = bp.Useless

const FRAME_MAGIC int = 0xB1

type PayloadType uint8

const (
	PAYLOAD_TYPE_UNKNOWN   PayloadType = 0
	PAYLOAD_TYPE_DRONE                 = 1
	PAYLOAD_TYPE_HEARTBEAT             = 2
	PAYLOAD_TYPE_COMMAND               = 3
	PAYLOAD_TYPE_FLIGHT                = 4
	PAYLOAD_TYPE_POSITION              = 5
	PAYLOAD_TYPE_MOVEMENT              = 6
	PAYLOAD_TYPE_RESULT                = 7
)

func (m PayloadType) BpProcessor() bp.Processor {
	return bp.NewEnumProcessor(bp.NewUint(5))
}

func (v PayloadType) String() string {
	switch v {
	case 0:
		return "PAYLOAD_TYPE_UNKNOWN"
	case 1:
		return "PAYLOAD_TYPE_DRONE"
	case 2:
		return "PAYLOAD_TYPE_HEARTBEAT"
	case 3:
		return "PAYLOAD_TYPE_COMMAND"
	case 4:
		return "PAYLOAD_TYPE_FLIGHT"
	case 5:
		return "PAYLOAD_TYPE_POSITION"
	case 6:
		return "PAYLOAD_TYPE_MOVEMENT"
	case 7:
		return "PAYLOAD_TYPE_RESULT"
	default:
		return "PayloadType(" + formatInt(int64(v), 10) + ")"
	}
}

type ProtocolVersion uint8

const (
	PROTOCOL_VERSION_UNKNOWN ProtocolVersion = 0
	PROTOCOL_VERSION_V1                      = 1
)

func (m ProtocolVersion) BpProcessor() bp.Processor {
	return bp.NewEnumProcessor(bp.NewUint(3))
}

func (v ProtocolVersion) String() string {
	switch v {
	case 0:
		return "PROTOCOL_VERSION_UNKNOWN"
	case 1:
		return "PROTOCOL_VERSION_V1"
	default:
		return "ProtocolVersion(" + formatInt(int64(v), 10) + ")"
	}
}

type FrameHeader struct {
	Magic         uint8           `json:"magic"`
	Version       ProtocolVersion `json:"version"`
	PayloadType   PayloadType     `json:"payload_type"`
	PayloadLength uint16          `json:"payload_length"`
}

const BYTES_LENGTH_FRAMEHEADER uint32 = 4

func (m *FrameHeader) Size() uint32 { return BYTES_LENGTH_FRAMEHEADER }

func (m *FrameHeader) String() string {
	v, _ := jsonMarshal(m)
	return string(v)
}

func (m *FrameHeader) Encode() []byte {
	ctx := bp.NewEncodeContext(int(m.Size()))
	m.BpProcessor().Process(ctx, nil, m)
	return ctx.Buffer()
}

func (m *FrameHeader) Decode(s []byte) {
	ctx := bp.NewDecodeContext(s)
	m.BpProcessor().Process(ctx, nil, m)
}

func (m *FrameHeader) BpProcessor() bp.Processor {
	fieldDescriptors := []*bp.MessageFieldProcessor{
		bp.NewMessageFieldProcessor(1, bp.NewUint(8)),
		bp.NewMessageFieldProcessor(2, (ProtocolVersion(0)).BpProcessor()),
		bp.NewMessageFieldProcessor(3, (PayloadType(0)).BpProcessor()),
		bp.NewMessageFieldProcessor(4, bp.NewUint(16)),
	}
	return bp.NewMessageProcessor(false, 32, fieldDescriptors)
}

func (m *FrameHeader) BpGetAccessor(di *bp.DataIndexer) bp.Accessor {
	switch di.F() {
	default:
		return nil
	}
}

func (m *FrameHeader) BpSetByte(di *bp.DataIndexer, lshift int, bt byte) {
	switch di.F() {
	case 1:
		m.Magic |= (uint8(bt) << lshift)
	case 2:
		m.Version |= (ProtocolVersion(bt) << lshift)
	case 3:
		m.PayloadType |= (PayloadType(bt) << lshift)
	case 4:
		m.PayloadLength |= (uint16(bt) << lshift)
	default:
		return
	}
}

func (m *FrameHeader) BpGetByte(di *bp.DataIndexer, rshift int) byte {
	switch di.F() {
	case 1:
		return byte(m.Magic >> rshift)
	case 2:
		return byte(m.Version >> rshift)
	case 3:
		return byte(m.PayloadType >> rshift)
	case 4:
		return byte(m.PayloadLength >> rshift)
	default:
		return byte(0)
	}
}

func (m *FrameHeader) BpProcessInt(di *bp.DataIndexer) {
	switch di.F() {
	default:
		return
	}
}
