// Code generated by bitproto-go native renderer (experimental). DO NOT EDIT.

package frameheader

import (
	"encoding/json"
	"math"
	bp "github.com/hit9/bitproto/lib/go"
)

var jsonMarshal = json.Marshal
var _ = bp.Useless

const BP_FLOAT_SCALE float64 = 100000000.0

func BpFloatToInt32(v float64) int32 {
	s := v * BP_FLOAT_SCALE
	if s > float64(math.MaxInt32) {
		return math.MaxInt32
	}
	if s < float64(math.MinInt32) {
		return math.MinInt32
	}
	return int32(math.Round(s))
}

func BpInt32ToFloat(v int32) float64 {
	return float64(v) / BP_FLOAT_SCALE
}

type PayloadType uint8

const (
	PAYLOAD_TYPE_UNKNOWN PayloadType = 0
	PAYLOAD_TYPE_DRONE = 1
)

func (m PayloadType) BpProcessor() bp.Processor {
	return bp.NewEnumProcessor(bp.NewUint(8))
}

type FrameHeader struct {
	Magic uint8 `json:"magic"`
	PayloadType PayloadType `json:"payload_type"`
	PayloadLength uint16 `json:"payload_length"`
}

const BYTES_LENGTH_FRAMEHEADER uint32 = 4

func (m *FrameHeader) Size() uint32 { return BYTES_LENGTH_FRAMEHEADER }

func (m *FrameHeader) String() string {
	v, _ := jsonMarshal(m)
	return string(v)
}

func (m *FrameHeader) Encode() []byte {
	ctx := bp.NewEncodeContext(int(m.Size()))
	m.BpProcessor().Process(ctx, nil, m)
	return ctx.Buffer()
}

func (m *FrameHeader) Decode(s []byte) {
	ctx := bp.NewDecodeContext(s)
	m.BpProcessor().Process(ctx, nil, m)
}

func (m *FrameHeader) BpProcessor() bp.Processor {
	fieldDescriptors := []*bp.MessageFieldProcessor{
		bp.NewMessageFieldProcessor(1, bp.NewUint(8)),
		bp.NewMessageFieldProcessor(2, (PayloadType(0)).BpProcessor()),
		bp.NewMessageFieldProcessor(3, bp.NewUint(16)),
	}
	return bp.NewMessageProcessor(false, 32, fieldDescriptors)
}

func (m *FrameHeader) BpGetAccessor(di *bp.DataIndexer) bp.Accessor {
	switch di.F() {
	default:
		return nil
	}
}

func (m *FrameHeader) BpSetByte(di *bp.DataIndexer, lshift int, bt byte) {
	switch di.F() {
	case 1:
		m.Magic |= (uint8(bt) << lshift)
	case 2:
		m.PayloadType |= (PayloadType(bt) << lshift)
	case 3:
		m.PayloadLength |= (uint16(bt) << lshift)
	default:
		return
	}
}

func (m *FrameHeader) BpGetByte(di *bp.DataIndexer, rshift int) byte {
	switch di.F() {
	case 1:
		return byte(m.Magic >> rshift)
	case 2:
		return byte(m.PayloadType >> rshift)
	case 3:
		return byte(m.PayloadLength >> rshift)
	default:
		return byte(0)
	}
}

func (m *FrameHeader) BpProcessInt(di *bp.DataIndexer) {
	switch di.F() {
	default:
		return
	}
}

